//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace steamdirectoryfinder.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("steamdirectoryfinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7za {
            get {
                object obj = ResourceManager.GetObject("_7za", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] addons {
            get {
                object obj = ResourceManager.GetObject("addons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrianOrr_Clouds {
            get {
                object obj = ResourceManager.GetObject("BrianOrr_Clouds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dl_ovr_runtime.bat
        ///hl2.exe
        ///hlds_steamgames.vdf
        ///third_party_legal_notices.txt
        ///thirdpartylegalnotices.txt
        ///bin\AdminServer.dll
        ///bin\avcodec-53.dll
        ///bin\avformat-53.dll
        ///bin\avutil-51.dll
        ///bin\base.fgd
        ///bin\basehaptics.txt
        ///bin\bsppack.dll
        ///bin\bspzip.exe
        ///bin\bugreporter.dll
        ///bin\bugreporter_filequeue.dll
        ///bin\bugreporter_public.dll
        ///bin\captioncompiler.exe
        ///bin\check_sdk_env.bat
        ///bin\chromehtml.dll
        ///bin\CmdSeq.wc
        ///bin\cstrike.fgd
        ///bin\datamodel.dll
        ///bin\demoinfo.exe
        ///bin\dmserializers.dll
        ///bin\dmxconvert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string files_to_delete_1_ {
            get {
                return ResourceManager.GetString("files_to_delete_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HLExtract {
            get {
                object obj = ResourceManager.GetObject("HLExtract", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HLLib {
            get {
                object obj = ResourceManager.GetObject("HLLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
