// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    public enum EConnectionPriority
    {
        KeConnectionPriorityLow = 0,
        KeConnectionPriorityMedium = 1,
        KeConnectionPriorityHigh = 2
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(601)]
    public struct CsClientApproveT
    {
        public const int KiCallback = 601;
        public SteamIdT m_SteamID;
        public uint m_uContentID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(602)]
    public struct CsClientDenyT
    {
        public const int KiCallback = 602;
        public SteamIdT m_SteamID;
        public uint m_uContentID;
        public EDenyReason m_eDenyReason;
    };
}