// This file is automatically generated.

namespace Steam4Net
{
    public enum ESteamServerType
    {
        ESteamValveCdKeyValidationServer = 0,
        ESteamHalfLifeMasterServer = 1,
        ESteamFriendsServer = 2,
        ESteamCserServer = 3,
        ESteamHalfLife2MasterServer = 4,
        ESteamRdkfMasterServer = 5,
        EMaxServerTypes = 6
    };
}