// This file is automatically generated.

namespace Steam4Net
{
    public enum ESteamSeekMethod
    {
        ESteamSeekMethodSet = 0,
        ESteamSeekMethodCur = 1,
        ESteamSeekMethodEnd = 2
    };
}