// This file is automatically generated.

namespace Steam4Net
{
    public enum EVoiceResult
    {
        KeVoiceResultOk = 0,
        KeVoiceResultNotInitialized = 1,
        KeVoiceResultNotRecording = 2,
        KeVoiceResultNoData = 3,
        KeVoiceResultBufferTooSmall = 4,
        KeVoiceResultDataCorrupted = 5,
        KeVoiceResultRestricted = 6,
        KeVoiceResultUnsupportedCodec = 7
    };
}