// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    public enum EAvatarSize
    {
        KeAvatarSize32X32 = 0,
        KeAvatarSize64X64 = 1,
        KeAvatarSize184X184 = 2,
        KeAvatarSizeMax = 3
    };

    public enum ECallState
    {
        KeCallStateUnknown = 0,
        KeCallStateWaiting = 1,
        KeCallStateDialing = 2,
        KeCallStateRinging = 3,
        KeCallStateInCall = 4
    };

    public enum EChatEntryType
    {
        KeChatEntryTypeInvalid = 0,
        KeChatEntryTypeChatMsg = 1,
        KeChatEntryTypeTyping = 2,
        KeChatEntryTypeInviteGame = 3,
        KeChatEntryTypeEmote = 4,
        KeChatEntryTypeLobbyGameStart = 5,
        KeChatEntryTypeLeftConversation = 6
    };

    public enum EFriendRelationship
    {
        KeFriendRelationshipNone = 0,
        KeFriendRelationshipBlocked = 1,
        KeFriendRelationshipRequestRecipient = 2,
        KeFriendRelationshipFriend = 3,
        KeFriendRelationshipRequestInitiator = 4,
        KeFriendRelationshipIgnored = 5,
        KeFriendRelationshipIgnoredFriend = 6,
        KeFriendRelationshipSuggested = 7,
        KeFriendRelationshipMax = 8
    };

    public enum EChatRoomType
    {
        KeChatRoomTypeFriend = 1,
        KeChatRoomTypeMuc = 2,
        KeChatRoomTypeLobby = 3
    };

    public enum EChatRoomVoiceStatus
    {
        EChatRoomVoiceStatusInvalid = -1,
        EChatRoomVoiceStatusBad = 0,
        EChatRoomVoiceStatusUnknownRoom = 1,
        EChatRoomVoiceStatusUnknownUser = 2,
        EChatRoomVoiceStatusNotSpeaking = 3,
        EChatRoomVoiceStatusConnectedSpeaking = 4,
        EChatRoomVoiceStatusConnectedSpeakingData = 5,
        EChatRoomVoiceStatusNotConnectedSpeaking = 6,
        EChatRoomVoiceStatusConnecting = 7,
        EChatRoomVoiceStatusUnreachable = 8,
        EChatRoomVoiceStatusDisconnected = 9,
        EChatRoomVoiceStatusCount = 10
    };

    public enum EClanRank
    {
        KeClanRankNone = 0,
        KeClanRankOwner = 1,
        KeClanRankOfficer = 2,
        KeClanRankMember = 3
    };

    public enum EClanRelationship
    {
        EClanRelationshipNone = 0,
        EClanRelationshipBlocked = 1,
        EClanRelationshipInvited = 2,
        EClanRelationshipMember = 3,
        EClanRelationshipKicked = 4
    };

    public enum EFriendFlags
    {
        KeFriendFlagNone = 0,
        KeFriendFlagBlocked = 1,
        KeFriendFlagFriendshipRequested = 2,
        KeFriendFlagImmediate = 4,
        KeFriendFlagClanMember = 8,
        KeFriendFlagOnGameServer = 16,
        KeFriendFlagRequestingFriendship = 128,
        KeFriendFlagRequestingInfo = 256,
        KeFriendFlagIgnored = 512,
        KeFriendFlagIgnoredFriend = 1024,
        KeFriendFlagSuggested = 2048,
        KeFriendFlagAll = 65535
    };

    public enum EPersonaState
    {
        KePersonaStateOffline = 0,
        KePersonaStateOnline = 1,
        KePersonaStateBusy = 2,
        KePersonaStateAway = 3,
        KePersonaStateSnooze = 4,
        KePersonaStateLookingToTrade = 5,
        KePersonaStateLookingToPlay = 6,
        KePersonaStateMax = 7
    };

    public enum EPersonaStateFlag
    {
        KePersonaStateFlagHasRichPresence = 1,
        KePersonaStateFlagInJoinableGame = 2
    };

    public enum EPersonaChange
    {
        KePersonaChangeName = 1,
        KePersonaChangeStatus = 2,
        KePersonaChangeComeOnline = 4,
        KePersonaChangeGoneOffline = 8,
        KePersonaChangeGamePlayed = 16,
        KePersonaChangeGameServer = 32,
        KePersonaChangeAvatar = 64,
        KePersonaChangeJoinedSource = 128,
        KePersonaChangeLeftSource = 256,
        KePersonaChangeRelationshipChanged = 512,
        KePersonaChangeNameFirstSet = 1024,
        KePersonaChangeFacebookInfo = 2048
    };

    public enum EChatPermission
    {
        KeChatPermissionClose = 1,
        KeChatPermissionInvite = 2,
        KeChatPermissionTalk = 8,
        KeChatPermissionKick = 16,
        KeChatPermissionMute = 32,
        KeChatPermissionSetMetadata = 64,
        KeChatPermissionChangePermissions = 128,
        KeChatPermissionBan = 256,
        KeChatPermissionChangeAccess = 512,
        KeChatPermissionEveryoneNotInClanDefault = 8,
        KeChatPermissionEveryoneDefault = 10,
        KeChatPermissionMemberDefault = 282,
        KeChatPermissionOfficerDefault = 282,
        KeChatPermissionOwnerDefault = 891,
        KeChatPermissionMask = 1019
    };

    public enum EChatRoomEnterResponse
    {
        KeChatRoomEnterResponseSuccess = 1,
        KeChatRoomEnterResponseDoesntExist = 2,
        KeChatRoomEnterResponseNotAllowed = 3,
        KeChatRoomEnterResponseFull = 4,
        KeChatRoomEnterResponseError = 5,
        KeChatRoomEnterResponseBanned = 6,
        KeChatRoomEnterResponseLimited = 7,
        KeChatRoomEnterResponseClanDisabled = 8,
        KeChatRoomEnterResponseCommunityBan = 9,
        KeChatRoomEnterResponseMemberBlockedYou = 10,
        KeChatRoomEnterResponseYouBlockedMember = 11,
        KeChatRoomEnterResponseNoRankingDataLobby = 12,
        KeChatRoomEnterResponseNoRankingDataUser = 13,
        KeChatRoomEnterResponseRankOutOfRange = 14
    };

    public enum EChatAction
    {
        KeChatActionInviteChat = 1,
        KeChatActionKick = 2,
        KeChatActionBan = 3,
        KeChatActionUnBan = 4,
        KeChatActionStartVoiceSpeak = 5,
        KeChatActionEndVoiceSpeak = 6,
        KeChatActionLockChat = 7,
        KeChatActionUnlockChat = 8,
        KeChatActionCloseChat = 9,
        KeChatActionSetJoinable = 10,
        KeChatActionSetUnjoinable = 11,
        KeChatActionSetOwner = 12,
        KeChatActionSetInvisibleToFriends = 13,
        KeChatActionSetVisibleToFriends = 14,
        KeChatActionSetModerated = 15,
        KeChatActionSetUnmoderated = 16
    };

    public enum EChatActionResult
    {
        KeChatActionResultSuccess = 1,
        KeChatActionResultError = 2,
        KeChatActionResultNotPermitted = 3,
        KeChatActionResultNotAllowedOnClanMember = 4,
        KeChatActionResultNotAllowedOnBannedUser = 5,
        KeChatActionResultNotAllowedOnChatOwner = 6,
        KeChatActionResultNotAllowedOnSelf = 7,
        KeChatActionResultChatDoesntExist = 8,
        KeChatActionResultChatFull = 9,
        KeChatActionResultVoiceSlotsFull = 10
    };

    public enum EUserRestriction
    {
        KnUserRestrictionNone = 0,
        KnUserRestrictionUnknown = 1,
        KnUserRestrictionAnyChat = 2,
        KnUserRestrictionVoiceChat = 4,
        KnUserRestrictionGroupChat = 8,
        KnUserRestrictionRating = 16,
        KnUserRestrictionGameInvites = 32,
        KnUserRestrictionTrading = 64
    };

    public enum EOverlayToStoreFlag
    {
        KeOverlayToStoreFlagNone = 0,
        KeOverlayToStoreFlagAddToCart = 1
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct FriendSessionStateInfoT
    {
        public uint m_uiOnlineSessionInstances;
        public byte m_uiPublishedToFriendsSessionInstance;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(304)]
    public struct PersonaStateChangeT
    {
        public const int KiCallback = 304;
        public SteamIdT m_ulSteamID;
        public EPersonaChange m_nChangeFlags;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(331)]
    public struct GameOverlayActivatedT
    {
        public const int KiCallback = 331;
        public byte m_bActive;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(332)]
    public struct GameServerChangeRequestedT
    {
        public const int KiCallback = 332;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)] public string m_rgchServer;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)] public string m_rgchPassword;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(333)]
    public struct GameLobbyJoinRequestedT
    {
        public const int KiCallback = 333;
        public SteamIdT m_steamIDLobby;
        public SteamIdT m_steamIDFriend;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(334)]
    public struct AvatarImageLoadedT
    {
        public const int KiCallback = 334;
        public SteamIdT m_steamID;
        public int m_iImage;
        public int m_iWide;
        public int m_iTall;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(335)]
    public struct ClanOfficerListResponseT
    {
        public const int KiCallback = 335;
        public SteamIdT m_steamIDClan;
        public int m_cOfficers;
        public byte m_bSuccess;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(336)]
    public struct FriendRichPresenceUpdateT
    {
        public const int KiCallback = 336;
        public SteamIdT m_steamIDFriend;
        public uint m_nAppID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(337)]
    public struct GameRichPresenceJoinRequestedT
    {
        public const int KiCallback = 337;
        public SteamIdT m_steamIDFriend;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)] public string m_rgchConnect;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(338)]
    public struct GameConnectedClanChatMsgT
    {
        public const int KiCallback = 338;
        public SteamIdT m_steamIDClanChat;
        public SteamIdT m_steamIDUser;
        public int m_iMessageID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(339)]
    public struct GameConnectedChatJoinT
    {
        public const int KiCallback = 339;
        public SteamIdT m_steamIDClanChat;
        public SteamIdT m_steamIDUser;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(340)]
    public struct GameConnectedChatLeaveT
    {
        public const int KiCallback = 340;
        public SteamIdT m_steamIDClanChat;
        public SteamIdT m_steamIDUser;
        [MarshalAs(UnmanagedType.I1)] public bool m_bKicked;
        [MarshalAs(UnmanagedType.I1)] public bool m_bDropped;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(341)]
    public struct DownloadClanActivityCountsResultT
    {
        public const int KiCallback = 341;
        [MarshalAs(UnmanagedType.I1)] public bool m_bSuccess;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(342)]
    public struct JoinClanChatRoomCompletionResultT
    {
        public const int KiCallback = 342;
        public SteamIdT m_steamIDClanChat;
        public EChatRoomEnterResponse m_eChatRoomEnterResponse;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(343)]
    public struct GameConnectedFriendChatMsgT
    {
        public const int KiCallback = 343;
        public SteamIdT m_steamIDUser;
        public int m_iMessageID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(344)]
    public struct FriendsGetFollowerCountT
    {
        public const int KiCallback = 344;
        public EResult m_eResult;
        public SteamIdT m_steamID;
        public int m_cCount;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(345)]
    public struct FriendsIsFollowingT
    {
        public const int KiCallback = 345;
        public EResult m_eResult;
        public SteamIdT m_steamID;
        [MarshalAs(UnmanagedType.I1)] public bool m_bIsFollowing;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(346)]
    public struct FriendsEnumerateFollowingListT
    {
        public const int KiCallback = 346;
        public EResult m_eResult;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 50)] public SteamIdT[] m_steamIDs;
        public int m_cSteamIDs;
        public int m_cTotalResults;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(347)]
    public struct SetPersonaNameResponseT
    {
        public const int KiCallback = 347;
        [MarshalAs(UnmanagedType.I1)] public bool m_bUnk1;
        [MarshalAs(UnmanagedType.I1)] public bool m_bUnk2;
        public EResult m_eResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(801)]
    public struct GameOverlayActivateRequestedT
    {
        public const int KiCallback = 801;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)] public string m_rgchDialog;
        public SteamIdT m_steamIDTarget;
        public uint m_nAppID;
        [MarshalAs(UnmanagedType.I1)] public bool m_bWebPage;
        public EOverlayToStoreFlag m_eFlag;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(802)]
    public struct ClanEventReceivedT
    {
        public const int KiCallback = 802;
        public ulong m_gidEvent;
        public ulong m_ulSteamIDClan;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)] public string m_rgchTitle;
        public uint m_nStartTime;
        public GameIdT m_GameID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(803)]
    public struct FriendAddedT
    {
        public const int KiCallback = 803;
        public EResult m_eResult;
        public ulong m_ulSteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(804)]
    public struct UserRequestingFriendshipT
    {
        public const int KiCallback = 804;
        public SteamIdT m_ulSteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(805)]
    public struct FriendChatMsgT
    {
        public const int KiCallback = 805;
        public SteamIdT m_ulFriendID;
        public SteamIdT m_ulSenderID;
        public byte m_eChatEntryType;
        public byte m_bLimitedAccount;
        public uint m_iChatID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(806)]
    public struct FriendInvitedT
    {
        public const int KiCallback = 806;
        public EResult m_eResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(807)]
    public struct ChatRoomInviteT
    {
        public const int KiCallback = 807;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDPatron;
        public SteamIdT m_ulSteamIDFriendChat;
        public EChatRoomType m_EChatRoomType;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string m_rgchChatRoomName;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(808)]
    public struct ChatRoomEnterT
    {
        public const int KiCallback = 808;
        public SteamIdT m_ulSteamIDChat;
        public EChatRoomType m_EChatRoomType;
        public ulong m_ulSteamIDOwner;
        public SteamIdT m_ulSteamIDClan;
        public SteamIdT m_ulSteamIDFriendChat;
        [MarshalAs(UnmanagedType.I1)] public bool m_bLocked;
        public uint m_rgfChatPermissions;
        public EChatRoomEnterResponse m_EChatRoomEnterResponse;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string m_rgchChatRoomName;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(809)]
    public struct ChatMemberStateChangeT
    {
        public const int KiCallback = 809;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDUserChanged;
        public EChatMemberStateChange m_rgfChatMemberStateChange;
        public ulong m_ulSteamIDMakingChange;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(810)]
    public struct ChatRoomMsgT
    {
        public const int KiCallback = 810;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDUser;
        public byte m_eChatEntryType;
        public uint m_iChatID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(811)]
    public struct ChatRoomDlgCloseT
    {
        public const int KiCallback = 811;
        public SteamIdT m_ulSteamIDChat;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(812)]
    public struct ChatRoomClosingT
    {
        public const int KiCallback = 812;
        public SteamIdT m_ulSteamIDChat;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(813)]
    public struct ChatRoomKickingT
    {
        public const int KiCallback = 813;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDAdmin;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(814)]
    public struct ChatRoomBanningT
    {
        public const int KiCallback = 814;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDAdmin;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(815)]
    public struct ChatRoomCreateT
    {
        public const int KiCallback = 815;
        public EResult m_eResult;
        public ulong m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDFriendChat;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(816)]
    public struct OpenChatDialogT
    {
        public const int KiCallback = 816;
        public SteamIdT m_ulSteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(817)]
    public struct ChatRoomActionResultT
    {
        public const int KiCallback = 817;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDUserActedOn;
        public EChatAction m_EChatAction;
        public EChatActionResult m_EChatActionResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(818)]
    public struct ChatRoomDlgSerializedT
    {
        public const int KiCallback = 818;
        public SteamIdT m_ulSteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(819)]
    public struct ClanInfoChangedT
    {
        public const int KiCallback = 819;
        public SteamIdT m_ulSteamID;
        [MarshalAs(UnmanagedType.I1)] public bool m_bNameChanged;
        [MarshalAs(UnmanagedType.I1)] public bool m_bAvatarChanged;
        [MarshalAs(UnmanagedType.I1)] public bool m_bAccountInfoChanged;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(820)]
    public struct ChatMemberInfoChangedT
    {
        public const int KiCallback = 820;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDUser;
        public uint m_rgfChatMemberPermissions;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(821)]
    public struct ChatRoomInfoChangedT
    {
        public const int KiCallback = 821;
        public SteamIdT m_ulSteamIDChat;
        public uint m_rgfChatRoomDetails;
        public ulong m_ulSteamIDMakingChange;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(822)]
    public struct SteamRackBouncingT
    {
        public const int KiCallback = 822;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(823)]
    public struct ChatRoomSpeakChangedT
    {
        public const int KiCallback = 823;
        public SteamIdT m_ulSteamIDChat;
        public SteamIdT m_ulSteamIDUser;
        [MarshalAs(UnmanagedType.I1)] public bool m_bSpeaking;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(824)]
    public struct NotifyIncomingCallT
    {
        public const int KiCallback = 824;
        public int m_Handle;
        public ulong m_ulSteamID;
        public SteamIdT m_ulSteamIDChat;
        [MarshalAs(UnmanagedType.I1)] public bool m_bIncoming;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(825)]
    public struct NotifyHangupT
    {
        public const int KiCallback = 825;
        public int m_Handle;
        public EVoiceResult m_eVoiceResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(826)]
    public struct NotifyRequestResumeT
    {
        public const int KiCallback = 826;
        public int m_Handle;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(827)]
    public struct NotifyChatRoomVoiceStateChangedT
    {
        public const int KiCallback = 827;
        public SteamIdT m_steamChatRoom;
        public SteamIdT m_steamUser;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(828)]
    public struct ChatRoomDlgUiChangeT
    {
        public const int KiCallback = 828;
        public SteamIdT m_SteamIDChat;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowAvatars;
        [MarshalAs(UnmanagedType.I1)] public bool m_bBeepOnNewMsg;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowSteamIDs;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowTimestampOnNewMsg;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(829)]
    public struct VoiceCallInitiatedT
    {
        public const int KiCallback = 829;
        public ulong MulSteamIDUser;
        public ulong MulSteamIDFriend;
        public int m_hVoiceCall;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(830)]
    public struct FriendIgnoredT
    {
        public const int KiCallback = 830;
        public EResult m_eResult;
        public ulong m_ulSteamID;
        public SteamIdT m_ulSteamIDFriend;
        [MarshalAs(UnmanagedType.I1)] public bool m_bIgnored;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(831)]
    public struct VoiceInputDeviceChangedT
    {
        public const int KiCallback = 831;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(832)]
    public struct VoiceEnabledStateChangedT
    {
        public const int KiCallback = 832;
        [MarshalAs(UnmanagedType.I1)] public bool m_bVoiceEnabled;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(833)]
    public struct FriendsWhoPlayGameUpdateT
    {
        public const int KiCallback = 833;
        public GameIdT m_gameID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(834)]
    public struct FriendProfileInfoResponseT
    {
        public const int KiCallback = 834;
        public SteamIdT m_steamIDFriend;
        public EResult m_eResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(835)]
    public struct RichInviteReceivedT
    {
        public const int KiCallback = 835;
        public SteamIdT m_steamIDFriend;
        public uint m_nAppID;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)] public string m_rgchConnect;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(836)]
    public struct FriendsMenuChangeT
    {
        public const int KiCallback = 836;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowAvatars;
        [MarshalAs(UnmanagedType.I1)] public bool m_bSortByName;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowOnlineFriendsOnly;
        [MarshalAs(UnmanagedType.I1)] public bool m_bShowUntaggedFriends;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(837)]
    public struct TradeInviteReceivedT
    {
        public const int KiCallback = 837;
        public SteamIdT m_steamIDPartner;
        public uint m_unTradeRequestID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(838)]
    public struct TradeInviteResponseT
    {
        public const int KiCallback = 838;
        public SteamIdT m_steamIDPartner;
        public uint m_eResponse;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(839)]
    public struct TradeStartSessionT
    {
        public const int KiCallback = 839;
        public SteamIdT m_steamIDPartner;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(840)]
    public struct TradeInviteCanceledT
    {
        public const int KiCallback = 840;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(841)]
    public struct GameUsingVoiceT
    {
        public const int KiCallback = 841;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(842)]
    public struct FriendsGroupCreatedT
    {
        public const int KiCallback = 842;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(843)]
    public struct FriendsGroupDeletedT
    {
        public const int KiCallback = 843;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(844)]
    public struct FriendsGroupRenamedT
    {
        public const int KiCallback = 844;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(845)]
    public struct FriendsGroupMemberAddedT
    {
        public const int KiCallback = 845;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(846)]
    public struct FriendsGroupMemberRemovedT
    {
        public const int KiCallback = 846;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(847)]
    public struct NameHistoryResponseT
    {
        public const int KiCallback = 847;
        public int m_cSuccessfulLookups;
        public int m_cFailedLookups;
    };
}