// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    public enum EDenyReason
    {
        KeDenyInvalid = 0,
        KeDenyInvalidVersion = 1,
        KeDenyGeneric = 2,
        KeDenyNotLoggedOn = 3,
        KeDenyNoLicense = 4,
        KeDenyCheater = 5,
        KeDenyLoggedInElseWhere = 6,
        KeDenyUnknownText = 7,
        KeDenyIncompatibleAnticheat = 8,
        KeDenyMemoryCorruption = 9,
        KeDenyIncompatibleSoftware = 10,
        KeDenySteamConnectionLost = 11,
        KeDenySteamConnectionError = 12,
        KeDenySteamResponseTimedOut = 13,
        KeDenySteamValidationStalled = 14,
        KeDenySteamOwnerLeftGuestUser = 15
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(201)]
    public struct GsClientApproveT
    {
        public const int KiCallback = 201;
        public SteamIdT m_SteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(202)]
    public struct GsClientDenyT
    {
        public const int KiCallback = 202;
        public SteamIdT m_SteamID;
        public EDenyReason m_eDenyReason;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
        public string m_pchOptionalText;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(203)]
    public struct GsClientKickT
    {
        public const int KiCallback = 203;
        public SteamIdT m_SteamID;
        public EDenyReason m_eDenyReason;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(204)]
    public struct GsClientSteam2DenyT
    {
        public const int KiCallback = 204;
        public uint m_UserID;
        public ESteamError m_eSteamError;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(205)]
    public struct GsClientSteam2AcceptT
    {
        public const int KiCallback = 205;
        public uint m_UserID;
        public ulong m_SteamID;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(206)]
    public struct GsClientAchievementStatusT
    {
        public const int KiCallback = 206;
        public SteamIdT m_SteamID;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
        public string m_pchAchievement;

        [MarshalAs(UnmanagedType.I1)]
        public bool m_bUnlocked;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(207)]
    public struct GsGameplayStatsT
    {
        public const int KiCallback = 207;
        public EResult m_eResult;
        public int m_nRank;
        public uint m_unTotalConnects;
        public uint m_unTotalMinutesPlayed;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(208)]
    public struct GsClientGroupStatusT
    {
        public const int KiCallback = 208;
        public SteamIdT m_SteamIDUser;
        public SteamIdT m_SteamIDGroup;

        [MarshalAs(UnmanagedType.I1)]
        public bool m_bMember;

        [MarshalAs(UnmanagedType.I1)]
        public bool m_bOfficer;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(209)]
    public struct GsReputationT
    {
        public const int KiCallback = 209;
        public EResult m_eResult;
        public uint m_unReputationScore;

        [MarshalAs(UnmanagedType.I1)]
        public bool m_bBanned;

        public uint m_unBannedIP;
        public ushort m_usBannedPort;
        public ulong m_ulBannedGameID;
        public uint m_unBanExpires;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(210)]
    public struct AssociateWithClanResultT
    {
        public const int KiCallback = 210;
        public EResult m_eResult;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(211)]
    public struct ComputeNewPlayerCompatibilityResultT
    {
        public const int KiCallback = 211;
        public EResult m_eResult;
        public int m_cPlayersThatDontLikeCandidate;
        public int m_cPlayersThatCandidateDoesntLike;
        public int m_cClanPlayersThatDontLikeCandidate;
        public SteamIdT m_SteamIDCandidate;
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    [InteropHelp.CallbackIdentityAttribute(115)]
    public struct GsPolicyResponseT
    {
        public const int KiCallback = 115;
        public byte m_bSecure;
    };
}