// This file is automatically generated.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class ClientDeviceAuthVTable
    {
        public IntPtr AuthorizeLocalDevice0;
        public IntPtr DeauthorizeLocalDevice1;
        public IntPtr GetDeviceAuthorizations2;
        public IntPtr GetDeviceAuthorizationInfo3;
        public IntPtr RequestAuthorizedDevicesInfo4;
        public IntPtr BIsAuthorizedLender5;
        public IntPtr GetSharedLibraryLockedBy6;
        private IntPtr DTorIClientDeviceAuth7;
    };

    [InteropHelp.InterfaceVersionAttribute("CLIENTDEVICEAUTH_INTERFACE_VERSION001")]
    public class ClientDeviceAuth : InteropHelp.NativeWrapper<ClientDeviceAuthVTable>
    {
        public ulong AuthorizeLocalDevice(string pubUnk, uint cubUnk)
        {
            return GetFunction<NativeAuthorizeLocalDeviceSu>(Functions.AuthorizeLocalDevice0)(ObjectAddress, pubUnk,
                cubUnk);
        }

        public ulong DeauthorizeLocalDevice(uint uUnk)
        {
            return GetFunction<NativeDeauthorizeLocalDeviceU>(Functions.DeauthorizeLocalDevice1)(ObjectAddress, uUnk);
        }

        public uint GetDeviceAuthorizations(ref ulong puUnk, uint uUnk)
        {
            return GetFunction<NativeGetDeviceAuthorizationsUu>(Functions.GetDeviceAuthorizations2)(ObjectAddress,
                ref puUnk, uUnk);
        }

        public bool GetDeviceAuthorizationInfo(ulong uUnk, ref uint puUnk1, ref uint puUnk2, ref uint puUnk3,
            ref bool pbUnk, StringBuilder pszUnk1, StringBuilder pszUnk2, StringBuilder pszUnk3)
        {
            return
                GetFunction<NativeGetDeviceAuthorizationInfoUuuubsisisi>(Functions.GetDeviceAuthorizationInfo3)(
                    ObjectAddress, uUnk, ref puUnk1, ref puUnk2, ref puUnk3, ref pbUnk, pszUnk1, pszUnk1.Capacity,
                    pszUnk2, pszUnk2.Capacity, pszUnk3, pszUnk3.Capacity);
        }

        public ulong RequestAuthorizedDevicesInfo()
        {
            return
                GetFunction<NativeRequestAuthorizedDevicesInfo>(Functions.RequestAuthorizedDevicesInfo4)(ObjectAddress);
        }

        public bool BIsAuthorizedLender(uint uUnk)
        {
            return GetFunction<NativeBIsAuthorizedLenderU>(Functions.BIsAuthorizedLender5)(ObjectAddress, uUnk);
        }

        public uint GetSharedLibraryLockedBy(uint uUnk)
        {
            return GetFunction<NativeGetSharedLibraryLockedByU>(Functions.GetSharedLibraryLockedBy6)(ObjectAddress, uUnk);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeAuthorizeLocalDeviceSu(IntPtr thisptr, string pubUnk, uint cubUnk);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeDeauthorizeLocalDeviceU(IntPtr thisptr, uint uUnk);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetDeviceAuthorizationsUu(IntPtr thisptr, ref ulong puUnk, uint uUnk);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetDeviceAuthorizationInfoUuuubsisisi(
            IntPtr thisptr, ulong uUnk, ref uint puUnk1, ref uint puUnk2, ref uint puUnk3, ref bool pbUnk,
            StringBuilder pszUnk1, int iUnk1, StringBuilder pszUnk2, int iUnk2, StringBuilder pszUnk3, int iUnk3);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeRequestAuthorizedDevicesInfo(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeBIsAuthorizedLenderU(IntPtr thisptr, uint uUnk);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetSharedLibraryLockedByU(IntPtr thisptr, uint uUnk);
    };
}