// This file is automatically generated.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class ClientMatchmakingVTable
    {
        public IntPtr GetFavoriteGameCount0;
        public IntPtr GetFavoriteGame1;
        public IntPtr AddFavoriteGame2;
        public IntPtr RemoveFavoriteGame3;
        public IntPtr RequestLobbyList4;
        public IntPtr AddRequestLobbyListStringFilter5;
        public IntPtr AddRequestLobbyListNumericalFilter6;
        public IntPtr AddRequestLobbyListNearValueFilter7;
        public IntPtr AddRequestLobbyListFilterSlotsAvailable8;
        public IntPtr AddRequestLobbyListDistanceFilter9;
        public IntPtr AddRequestLobbyListResultCountFilter10;
        public IntPtr AddRequestLobbyListCompatibleMembersFilter11;
        public IntPtr GetLobbyByIndex12;
        public IntPtr CreateLobby13;
        public IntPtr JoinLobby14;
        public IntPtr LeaveLobby15;
        public IntPtr InviteUserToLobby16;
        public IntPtr GetNumLobbyMembers17;
        public IntPtr GetLobbyMemberByIndex18;
        public IntPtr GetLobbyData19;
        public IntPtr SetLobbyData20;
        public IntPtr GetLobbyDataCount21;
        public IntPtr GetLobbyDataByIndex22;
        public IntPtr DeleteLobbyData23;
        public IntPtr GetLobbyMemberData24;
        public IntPtr SetLobbyMemberData25;
        public IntPtr SendLobbyChatMsg26;
        public IntPtr GetLobbyChatEntry27;
        public IntPtr RequestLobbyData28;
        public IntPtr SetLobbyGameServer29;
        public IntPtr GetLobbyGameServer30;
        public IntPtr SetLobbyMemberLimit31;
        public IntPtr GetLobbyMemberLimit32;
        public IntPtr SetLobbyVoiceEnabled33;
        public IntPtr RequestFriendsLobbies34;
        public IntPtr SetLobbyType35;
        public IntPtr SetLobbyJoinable36;
        public IntPtr GetLobbyOwner37;
        public IntPtr SetLobbyOwner38;
        public IntPtr SetLinkedLobby39;
        public IntPtr BeginGMSQuery40;
        public IntPtr PollGMSQuery41;
        public IntPtr GetGMSQueryResults42;
        public IntPtr ReleaseGMSQuery43;
        public IntPtr SendGameServerPingSample44;
        private IntPtr DTorIClientMatchmaking45;
    };

    [InteropHelp.InterfaceVersionAttribute("CLIENTMATCHMAKING_INTERFACE_VERSION001")]
    public class ClientMatchmaking : InteropHelp.NativeWrapper<ClientMatchmakingVTable>
    {
        public int GetFavoriteGameCount()
        {
            return GetFunction<NativeGetFavoriteGameCount>(Functions.GetFavoriteGameCount0)(ObjectAddress);
        }

        public bool GetFavoriteGame(int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort,
            ref ushort pnQueryPort, ref uint punFlags, ref uint pRTime32LastPlayedOnServer)
        {
            return GetFunction<NativeGetFavoriteGameIuuuuuu>(Functions.GetFavoriteGame1)(ObjectAddress, iGame,
                ref pnAppId, ref pnIp, ref pnConnPort, ref pnQueryPort, ref punFlags, ref pRTime32LastPlayedOnServer);
        }

        public int AddFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer)
        {
            return GetFunction<NativeAddFavoriteGameUuuuuu>(Functions.AddFavoriteGame2)(ObjectAddress, nAppId, nIp,
                nConnPort, nQueryPort, unFlags, rTime32LastPlayedOnServer);
        }

        public bool RemoveFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags)
        {
            return GetFunction<NativeRemoveFavoriteGameUuuuu>(Functions.RemoveFavoriteGame3)(ObjectAddress, nAppId, nIp,
                nConnPort, nQueryPort, unFlags);
        }

        public ulong RequestLobbyList()
        {
            return GetFunction<NativeRequestLobbyList>(Functions.RequestLobbyList4)(ObjectAddress);
        }

        public void AddRequestLobbyListStringFilter(string pchKeyToMatch, string pchValueToMatch,
            ELobbyComparison eComparisonType)
        {
            GetFunction<NativeAddRequestLobbyListStringFilterSse>(Functions.AddRequestLobbyListStringFilter5)(
                ObjectAddress, pchKeyToMatch, pchValueToMatch, eComparisonType);
        }

        public void AddRequestLobbyListNumericalFilter(string pchKeyToMatch, int nValueToMatch,
            ELobbyComparison eComparisonType)
        {
            GetFunction<NativeAddRequestLobbyListNumericalFilterSie>(Functions.AddRequestLobbyListNumericalFilter6)(
                ObjectAddress, pchKeyToMatch, nValueToMatch, eComparisonType);
        }

        public void AddRequestLobbyListNearValueFilter(string pchKeyToMatch, int nValueToBeCloseTo)
        {
            GetFunction<NativeAddRequestLobbyListNearValueFilterSi>(Functions.AddRequestLobbyListNearValueFilter7)(
                ObjectAddress, pchKeyToMatch, nValueToBeCloseTo);
        }

        public void AddRequestLobbyListFilterSlotsAvailable(int nSlotsAvailable)
        {
            GetFunction<NativeAddRequestLobbyListFilterSlotsAvailableI>(
                Functions.AddRequestLobbyListFilterSlotsAvailable8)(ObjectAddress, nSlotsAvailable);
        }

        public void AddRequestLobbyListDistanceFilter(ELobbyDistanceFilter filter)
        {
            GetFunction<NativeAddRequestLobbyListDistanceFilterE>(Functions.AddRequestLobbyListDistanceFilter9)(
                ObjectAddress, filter);
        }

        public void AddRequestLobbyListResultCountFilter(int cMaxResults)
        {
            GetFunction<NativeAddRequestLobbyListResultCountFilterI>(Functions.AddRequestLobbyListResultCountFilter10)(
                ObjectAddress, cMaxResults);
        }

        public void AddRequestLobbyListCompatibleMembersFilter(CSteamId steamId)
        {
            GetFunction<NativeAddRequestLobbyListCompatibleMembersFilterC>(
                Functions.AddRequestLobbyListCompatibleMembersFilter11)(ObjectAddress, steamId.ConvertToUint64());
        }

        public CSteamId GetLobbyByIndex(int iLobby)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyByIndexI>(Functions.GetLobbyByIndex12)(ObjectAddress, ref ret, iLobby);
            return new CSteamId(ret);
        }

        public ulong CreateLobby(ELobbyType eLobbyType, int cMaxMembers)
        {
            return GetFunction<NativeCreateLobbyEi>(Functions.CreateLobby13)(ObjectAddress, eLobbyType, cMaxMembers);
        }

        public ulong JoinLobby(CSteamId steamIdLobby)
        {
            return GetFunction<NativeJoinLobbyC>(Functions.JoinLobby14)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public void LeaveLobby(CSteamId steamIdLobby)
        {
            GetFunction<NativeLeaveLobbyC>(Functions.LeaveLobby15)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public bool InviteUserToLobby(CSteamId steamIdLobby, CSteamId steamIdInvitee)
        {
            return GetFunction<NativeInviteUserToLobbyCc>(Functions.InviteUserToLobby16)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdInvitee.ConvertToUint64());
        }

        public int GetNumLobbyMembers(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetNumLobbyMembersC>(Functions.GetNumLobbyMembers17)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public CSteamId GetLobbyMemberByIndex(CSteamId steamIdLobby, int iMember)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyMemberByIndexCi>(Functions.GetLobbyMemberByIndex18)(ObjectAddress, ref ret,
                steamIdLobby.ConvertToUint64(), iMember);
            return new CSteamId(ret);
        }

        public string GetLobbyData(CSteamId steamIdLobby, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetLobbyDataCs>(Functions.GetLobbyData19)(ObjectAddress,
                        steamIdLobby.ConvertToUint64(), pchKey)));
        }

        public bool SetLobbyData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            return GetFunction<NativeSetLobbyDataCss>(Functions.SetLobbyData20)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey, pchValue);
        }

        public int GetLobbyDataCount(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetLobbyDataCountC>(Functions.GetLobbyDataCount21)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public bool GetLobbyDataByIndex(CSteamId steamIdLobby, int iLobbyData, StringBuilder pchKey,
            StringBuilder pchValue)
        {
            return GetFunction<NativeGetLobbyDataByIndexCisisi>(Functions.GetLobbyDataByIndex22)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), iLobbyData, pchKey, pchKey.Capacity, pchValue, pchValue.Capacity);
        }

        public bool DeleteLobbyData(CSteamId steamIdLobby, string pchKey)
        {
            return GetFunction<NativeDeleteLobbyDataCs>(Functions.DeleteLobbyData23)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey);
        }

        public string GetLobbyMemberData(CSteamId steamIdLobby, CSteamId steamIdUser, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetLobbyMemberDataCcs>(Functions.GetLobbyMemberData24)(ObjectAddress,
                            steamIdLobby.ConvertToUint64(), steamIdUser.ConvertToUint64(), pchKey)));
        }

        public void SetLobbyMemberData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            GetFunction<NativeSetLobbyMemberDataCss>(Functions.SetLobbyMemberData25)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey, pchValue);
        }

        public bool SendLobbyChatMsg(CSteamId steamIdLobby, byte[] pvMsgBody)
        {
            return GetFunction<NativeSendLobbyChatMsgCbi>(Functions.SendLobbyChatMsg26)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pvMsgBody, pvMsgBody.Length);
        }

        public int GetLobbyChatEntry(CSteamId steamIdLobby, int iChatId, ref CSteamId pSteamIdUser, byte[] pvData,
            ref EChatEntryType peChatEntryType)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetLobbyChatEntryCicbie>(Functions.GetLobbyChatEntry27)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), iChatId, ref s0, pvData, pvData.Length, ref peChatEntryType);
            pSteamIdUser = new CSteamId(s0);
            return result;
        }

        public bool RequestLobbyData(CSteamId steamIdLobby)
        {
            return GetFunction<NativeRequestLobbyDataC>(Functions.RequestLobbyData28)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public void SetLobbyGameServer(CSteamId steamIdLobby, uint unGameServerIp, ushort unGameServerPort,
            CSteamId steamIdGameServer)
        {
            GetFunction<NativeSetLobbyGameServerCuuc>(Functions.SetLobbyGameServer29)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), unGameServerIp, unGameServerPort, steamIdGameServer.ConvertToUint64());
        }

        public bool GetLobbyGameServer(CSteamId steamIdLobby, ref uint punGameServerIp, ref ushort punGameServerPort,
            ref CSteamId psteamIdGameServer)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetLobbyGameServerCuuc>(Functions.GetLobbyGameServer30)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), ref punGameServerIp, ref punGameServerPort, ref s0);
            psteamIdGameServer = new CSteamId(s0);
            return result;
        }

        public bool SetLobbyMemberLimit(CSteamId steamIdLobby, int cMaxMembers)
        {
            return GetFunction<NativeSetLobbyMemberLimitCi>(Functions.SetLobbyMemberLimit31)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), cMaxMembers);
        }

        public int GetLobbyMemberLimit(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetLobbyMemberLimitC>(Functions.GetLobbyMemberLimit32)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public void SetLobbyVoiceEnabled(CSteamId steamIdLobby, bool bVoiceEnabled)
        {
            GetFunction<NativeSetLobbyVoiceEnabledCb>(Functions.SetLobbyVoiceEnabled33)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), bVoiceEnabled);
        }

        public bool RequestFriendsLobbies()
        {
            return GetFunction<NativeRequestFriendsLobbies>(Functions.RequestFriendsLobbies34)(ObjectAddress);
        }

        public bool SetLobbyType(CSteamId steamIdLobby, ELobbyType eLobbyType)
        {
            return GetFunction<NativeSetLobbyTypeCe>(Functions.SetLobbyType35)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), eLobbyType);
        }

        public bool SetLobbyJoinable(CSteamId steamIdLobby, bool bLobbyJoinable)
        {
            return GetFunction<NativeSetLobbyJoinableCb>(Functions.SetLobbyJoinable36)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), bLobbyJoinable);
        }

        public CSteamId GetLobbyOwner(CSteamId steamIdLobby)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyOwnerC>(Functions.GetLobbyOwner37)(ObjectAddress, ref ret,
                steamIdLobby.ConvertToUint64());
            return new CSteamId(ret);
        }

        public bool SetLobbyOwner(CSteamId steamIdLobby, CSteamId steamIdNewOwner)
        {
            return GetFunction<NativeSetLobbyOwnerCc>(Functions.SetLobbyOwner38)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdNewOwner.ConvertToUint64());
        }

        public bool SetLinkedLobby(CSteamId steamIdLobby, CSteamId steamIdLobby2)
        {
            return GetFunction<NativeSetLinkedLobbyCc>(Functions.SetLinkedLobby39)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdLobby2.ConvertToUint64());
        }

        public ulong BeginGmsQuery(uint nAppId, int iRegionCode, string szFilterText)
        {
            return GetFunction<NativeBeginGmsQueryUis>(Functions.BeginGMSQuery40)(ObjectAddress, nAppId, iRegionCode,
                szFilterText);
        }

        public int PollGmsQuery(ulong ullGmsQuery)
        {
            return GetFunction<NativePollGmsQueryU>(Functions.PollGMSQuery41)(ObjectAddress, ullGmsQuery);
        }

        public int GetGmsQueryResults(ulong ullGmsQuery, ref GmsQueryResultT pGmsQueryResults,
            int nResultBufSizeInBytes)
        {
            return GetFunction<NativeGetGmsQueryResultsUgi>(Functions.GetGMSQueryResults42)(ObjectAddress, ullGmsQuery,
                ref pGmsQueryResults, nResultBufSizeInBytes);
        }

        public void ReleaseGmsQuery(ulong ullGmsQuery)
        {
            GetFunction<NativeReleaseGmsQueryU>(Functions.ReleaseGMSQuery43)(ObjectAddress, ullGmsQuery);
        }

        public void SendGameServerPingSample(uint unAppId, int nSamples, ref PingSampleT pSamples)
        {
            GetFunction<NativeSendGameServerPingSampleUip>(Functions.SendGameServerPingSample44)(ObjectAddress, unAppId,
                nSamples, ref pSamples);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFavoriteGameCount(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFavoriteGameIuuuuuu(
            IntPtr thisptr, int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort, ref ushort pnQueryPort,
            ref uint punFlags, ref uint pRTime32LastPlayedOnServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeAddFavoriteGameUuuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRemoveFavoriteGameUuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeRequestLobbyList(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListStringFilterSse(
            IntPtr thisptr, string pchKeyToMatch, string pchValueToMatch, ELobbyComparison eComparisonType);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListNumericalFilterSie(
            IntPtr thisptr, string pchKeyToMatch, int nValueToMatch, ELobbyComparison eComparisonType);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListNearValueFilterSi(
            IntPtr thisptr, string pchKeyToMatch, int nValueToBeCloseTo);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListFilterSlotsAvailableI(IntPtr thisptr, int nSlotsAvailable);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListDistanceFilterE(IntPtr thisptr, ELobbyDistanceFilter filter);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListResultCountFilterI(IntPtr thisptr, int cMaxResults);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListCompatibleMembersFilterC(IntPtr thisptr, ulong steamId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyByIndexI(IntPtr thisptr, ref ulong retarg, int iLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeCreateLobbyEi(IntPtr thisptr, ELobbyType eLobbyType, int cMaxMembers);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeJoinLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeLeaveLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeInviteUserToLobbyCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdInvitee);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetNumLobbyMembersC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyMemberByIndexCi(
            IntPtr thisptr, ref ulong retarg, ulong steamIdLobby, int iMember);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyDataCs(IntPtr thisptr, ulong steamIdLobby, string pchKey);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyDataCss(IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyDataCountC(IntPtr thisptr, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetLobbyDataByIndexCisisi(
            IntPtr thisptr, ulong steamIdLobby, int iLobbyData, StringBuilder pchKey, int cchKeyBufferSize,
            StringBuilder pchValue, int cchValueBufferSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeDeleteLobbyDataCs(IntPtr thisptr, ulong steamIdLobby, string pchKey);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyMemberDataCcs(
            IntPtr thisptr, ulong steamIdLobby, ulong steamIdUser, string pchKey);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyMemberDataCss(
            IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendLobbyChatMsgCbi(
            IntPtr thisptr, ulong steamIdLobby, byte[] pvMsgBody, int cubMsgBody);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyChatEntryCicbie(
            IntPtr thisptr, ulong steamIdLobby, int iChatId, ref ulong pSteamIdUser, byte[] pvData, int cubData,
            ref EChatEntryType peChatEntryType);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRequestLobbyDataC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyGameServerCuuc(
            IntPtr thisptr, ulong steamIdLobby, uint unGameServerIp, ushort unGameServerPort, ulong steamIdGameServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetLobbyGameServerCuuc(
            IntPtr thisptr, ulong steamIdLobby, ref uint punGameServerIp, ref ushort punGameServerPort,
            ref ulong psteamIdGameServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyMemberLimitCi(IntPtr thisptr, ulong steamIdLobby, int cMaxMembers);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyMemberLimitC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyVoiceEnabledCb(
            IntPtr thisptr, ulong steamIdLobby, [MarshalAs(UnmanagedType.I1)] bool bVoiceEnabled);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRequestFriendsLobbies(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyTypeCe(IntPtr thisptr, ulong steamIdLobby, ELobbyType eLobbyType);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyJoinableCb(
            IntPtr thisptr, ulong steamIdLobby, [MarshalAs(UnmanagedType.I1)] bool bLobbyJoinable);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyOwnerC(IntPtr thisptr, ref ulong retarg, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyOwnerCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdNewOwner);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLinkedLobbyCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdLobby2);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeBeginGmsQueryUis(IntPtr thisptr, uint nAppId, int iRegionCode, string szFilterText);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativePollGmsQueryU(IntPtr thisptr, ulong ullGmsQuery);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetGmsQueryResultsUgi(
            IntPtr thisptr, ulong ullGmsQuery, ref GmsQueryResultT pGmsQueryResults, int nResultBufSizeInBytes);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeReleaseGmsQueryU(IntPtr thisptr, ulong ullGmsQuery);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSendGameServerPingSampleUip(
            IntPtr thisptr, uint unAppId, int nSamples, ref PingSampleT pSamples);
    };
}