// This file is automatically generated.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class ClientAppsVTable
    {
        public IntPtr GetAppData0;
        public IntPtr GetInternalAppIDFromGameID1;
        public IntPtr GetAllOwnedMultiplayerApps2;
        public IntPtr GetAppDataSection3;
        public IntPtr RequestAppInfoUpdate4;
        public IntPtr NotifyAppEventTriggered5;
        public IntPtr NotifyDlcInstalled6;
        public IntPtr GetDLCCount7;
        public IntPtr BGetDLCDataByIndex8;
        public IntPtr BIsDlcInstalled9;
        private IntPtr DTorIClientApps10;
    };

    [InteropHelp.InterfaceVersionAttribute("CLIENTAPPS_INTERFACE_VERSION001")]
    public class ClientApps : InteropHelp.NativeWrapper<ClientAppsVTable>
    {
        public int GetAppData(uint unAppId, string pchKey, StringBuilder pchValue)
        {
            return GetFunction<NativeGetAppDataUssi>(Functions.GetAppData0)(ObjectAddress, unAppId, pchKey, pchValue,
                pchValue.Capacity);
        }

        public uint GetInternalAppIdFromGameId(CGameId nGameId)
        {
            return GetFunction<NativeGetInternalAppIdFromGameIdc>(Functions.GetInternalAppIDFromGameID1)(ObjectAddress,
                nGameId.ConvertToUint64());
        }

        public int GetAllOwnedMultiplayerApps(ref uint punAppIDs, int cAppIDsMax)
        {
            return GetFunction<NativeGetAllOwnedMultiplayerAppsUi>(Functions.GetAllOwnedMultiplayerApps2)(
                ObjectAddress, ref punAppIDs, cAppIDsMax);
        }

        public int GetAppDataSection(uint unAppId, EAppInfoSection eSection, byte[] pchBuffer, bool bSharedKvSymbols)
        {
            return GetFunction<NativeGetAppDataSectionUebib>(Functions.GetAppDataSection3)(ObjectAddress, unAppId,
                eSection, pchBuffer, pchBuffer.Length, bSharedKvSymbols);
        }

        public bool RequestAppInfoUpdate(ref uint pAppIDs, int nNumAppIDs)
        {
            return GetFunction<NativeRequestAppInfoUpdateUi>(Functions.RequestAppInfoUpdate4)(ObjectAddress, ref pAppIDs,
                nNumAppIDs);
        }

        public void NotifyAppEventTriggered(uint unAppId, EAppEvent eAppEvent)
        {
            GetFunction<NativeNotifyAppEventTriggeredUe>(Functions.NotifyAppEventTriggered5)(ObjectAddress, unAppId,
                eAppEvent);
        }

        public void NotifyDlcInstalled(uint unAppId)
        {
            GetFunction<NativeNotifyDlcInstalledU>(Functions.NotifyDlcInstalled6)(ObjectAddress, unAppId);
        }

        public int GetDlcCount(uint unAppId)
        {
            return GetFunction<NativeGetDlcCountU>(Functions.GetDLCCount7)(ObjectAddress, unAppId);
        }

        public bool BGetDlcDataByIndex(uint unAppId, int iDlc, ref uint pDlcAppId, ref bool pbAvailable,
            StringBuilder pchName)
        {
            return GetFunction<NativeBGetDlcDataByIndexUiubsi>(Functions.BGetDLCDataByIndex8)(ObjectAddress, unAppId,
                iDlc, ref pDlcAppId, ref pbAvailable, pchName, pchName.Capacity);
        }

        public bool BIsDlcInstalled(uint unDlcAppId, uint unGameAppId)
        {
            return GetFunction<NativeBIsDlcInstalledUu>(Functions.BIsDlcInstalled9)(ObjectAddress, unDlcAppId,
                unGameAppId);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetAppDataUssi(
            IntPtr thisptr, uint unAppId, string pchKey, StringBuilder pchValue, int cchValueMax);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetInternalAppIdFromGameIdc(IntPtr thisptr, ulong nGameId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetAllOwnedMultiplayerAppsUi(IntPtr thisptr, ref uint punAppIDs, int cAppIDsMax);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetAppDataSectionUebib(
            IntPtr thisptr, uint unAppId, EAppInfoSection eSection, byte[] pchBuffer, int cbBufferMax,
            [MarshalAs(UnmanagedType.I1)] bool bSharedKvSymbols);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRequestAppInfoUpdateUi(IntPtr thisptr, ref uint pAppIDs, int nNumAppIDs);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeNotifyAppEventTriggeredUe(IntPtr thisptr, uint unAppId, EAppEvent eAppEvent);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeNotifyDlcInstalledU(IntPtr thisptr, uint unAppId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetDlcCountU(IntPtr thisptr, uint unAppId);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeBGetDlcDataByIndexUiubsi(
            IntPtr thisptr, uint unAppId, int iDlc, ref uint pDlcAppId, ref bool pbAvailable, StringBuilder pchName,
            int cchNameBufferSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeBIsDlcInstalledUu(IntPtr thisptr, uint unDlcAppId, uint unGameAppId);
    };
}