// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamFriends003VTable
    {
        public IntPtr GetPersonaName0;
        public IntPtr SetPersonaName1;
        public IntPtr GetPersonaState2;
        public IntPtr GetFriendCount3;
        public IntPtr GetFriendByIndex4;
        public IntPtr GetFriendRelationship5;
        public IntPtr GetFriendPersonaState6;
        public IntPtr GetFriendPersonaName7;
        public IntPtr GetFriendAvatar8;
        public IntPtr GetFriendGamePlayed9;
        public IntPtr GetFriendPersonaNameHistory10;
        public IntPtr HasFriend11;
        public IntPtr GetClanCount12;
        public IntPtr GetClanByIndex13;
        public IntPtr GetClanName14;
        public IntPtr GetFriendCountFromSource15;
        public IntPtr GetFriendFromSourceByIndex16;
        public IntPtr IsUserInSource17;
        public IntPtr SetInGameVoiceSpeaking18;
        public IntPtr ActivateGameOverlay19;
        private IntPtr DTorISteamFriends00320;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamFriends003")]
    public class SteamFriends003 : InteropHelp.NativeWrapper<SteamFriends003VTable>
    {
        public string GetPersonaName()
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetPersonaName>(Functions.GetPersonaName0)(ObjectAddress)));
        }

        public void SetPersonaName(string pchPersonaName)
        {
            GetFunction<NativeSetPersonaNameS>(Functions.SetPersonaName1)(ObjectAddress, pchPersonaName);
        }

        public EPersonaState GetPersonaState()
        {
            return GetFunction<NativeGetPersonaState>(Functions.GetPersonaState2)(ObjectAddress);
        }

        public int GetFriendCount(EFriendFlags iFriendFlags)
        {
            return GetFunction<NativeGetFriendCountE>(Functions.GetFriendCount3)(ObjectAddress, iFriendFlags);
        }

        public CSteamId GetFriendByIndex(int iFriend, EFriendFlags iFriendFlags)
        {
            ulong ret = 0;
            GetFunction<NativeGetFriendByIndexIe>(Functions.GetFriendByIndex4)(ObjectAddress, ref ret, iFriend,
                iFriendFlags);
            return new CSteamId(ret);
        }

        public EFriendRelationship GetFriendRelationship(CSteamId steamIdFriend)
        {
            return GetFunction<NativeGetFriendRelationshipC>(Functions.GetFriendRelationship5)(ObjectAddress,
                steamIdFriend.ConvertToUint64());
        }

        public EPersonaState GetFriendPersonaState(CSteamId steamIdFriend)
        {
            return GetFunction<NativeGetFriendPersonaStateC>(Functions.GetFriendPersonaState6)(ObjectAddress,
                steamIdFriend.ConvertToUint64());
        }

        public string GetFriendPersonaName(CSteamId steamIdFriend)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetFriendPersonaNameC>(Functions.GetFriendPersonaName7)(ObjectAddress,
                            steamIdFriend.ConvertToUint64())));
        }

        public int GetFriendAvatar(CSteamId steamIdFriend)
        {
            return GetFunction<NativeGetFriendAvatarC>(Functions.GetFriendAvatar8)(ObjectAddress,
                steamIdFriend.ConvertToUint64());
        }

        public bool GetFriendGamePlayed(CSteamId steamIdFriend, ref ulong pulGameId, ref uint punGameIp,
            ref ushort pusGamePort, ref ushort pusQueryPort)
        {
            return GetFunction<NativeGetFriendGamePlayedCuuuu>(Functions.GetFriendGamePlayed9)(ObjectAddress,
                steamIdFriend.ConvertToUint64(), ref pulGameId, ref punGameIp, ref pusGamePort, ref pusQueryPort);
        }

        public string GetFriendPersonaNameHistory(CSteamId steamIdFriend, int iPersonaName)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetFriendPersonaNameHistoryCi>(Functions.GetFriendPersonaNameHistory10)(
                            ObjectAddress, steamIdFriend.ConvertToUint64(), iPersonaName)));
        }

        public bool HasFriend(CSteamId steamIdFriend, EFriendFlags iFriendFlags)
        {
            return GetFunction<NativeHasFriendCe>(Functions.HasFriend11)(ObjectAddress, steamIdFriend.ConvertToUint64(),
                iFriendFlags);
        }

        public int GetClanCount()
        {
            return GetFunction<NativeGetClanCount>(Functions.GetClanCount12)(ObjectAddress);
        }

        public CSteamId GetClanByIndex(int iClan)
        {
            ulong ret = 0;
            GetFunction<NativeGetClanByIndexI>(Functions.GetClanByIndex13)(ObjectAddress, ref ret, iClan);
            return new CSteamId(ret);
        }

        public string GetClanName(CSteamId steamIdClan)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetClanNameC>(Functions.GetClanName14)(ObjectAddress,
                        steamIdClan.ConvertToUint64())));
        }

        public int GetFriendCountFromSource(CSteamId steamIdSource)
        {
            return GetFunction<NativeGetFriendCountFromSourceC>(Functions.GetFriendCountFromSource15)(ObjectAddress,
                steamIdSource.ConvertToUint64());
        }

        public CSteamId GetFriendFromSourceByIndex(CSteamId steamIdSource, int iFriend)
        {
            ulong ret = 0;
            GetFunction<NativeGetFriendFromSourceByIndexCi>(Functions.GetFriendFromSourceByIndex16)(ObjectAddress,
                ref ret, steamIdSource.ConvertToUint64(), iFriend);
            return new CSteamId(ret);
        }

        public bool IsUserInSource(CSteamId steamIdUser, CSteamId steamIdSource)
        {
            return GetFunction<NativeIsUserInSourceCc>(Functions.IsUserInSource17)(ObjectAddress,
                steamIdUser.ConvertToUint64(), steamIdSource.ConvertToUint64());
        }

        public void SetInGameVoiceSpeaking(CSteamId steamIdUser, bool bSpeaking)
        {
            GetFunction<NativeSetInGameVoiceSpeakingCb>(Functions.SetInGameVoiceSpeaking18)(ObjectAddress,
                steamIdUser.ConvertToUint64(), bSpeaking);
        }

        public void ActivateGameOverlay(string pchDialog)
        {
            GetFunction<NativeActivateGameOverlayS>(Functions.ActivateGameOverlay19)(ObjectAddress, pchDialog);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetPersonaName(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetPersonaNameS(IntPtr thisptr, string pchPersonaName);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EPersonaState NativeGetPersonaState(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendCountE(IntPtr thisptr, EFriendFlags iFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetFriendByIndexIe(
            IntPtr thisptr, ref ulong retarg, int iFriend, EFriendFlags iFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EFriendRelationship NativeGetFriendRelationshipC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EPersonaState NativeGetFriendPersonaStateC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetFriendPersonaNameC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendAvatarC(IntPtr thisptr, ulong steamIdFriend);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFriendGamePlayedCuuuu(
            IntPtr thisptr, ulong steamIdFriend, ref ulong pulGameId, ref uint punGameIp, ref ushort pusGamePort,
            ref ushort pusQueryPort);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetFriendPersonaNameHistoryCi(
            IntPtr thisptr, ulong steamIdFriend, int iPersonaName);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeHasFriendCe(IntPtr thisptr, ulong steamIdFriend, EFriendFlags iFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetClanCount(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetClanByIndexI(IntPtr thisptr, ref ulong retarg, int iClan);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetClanNameC(IntPtr thisptr, ulong steamIdClan);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendCountFromSourceC(IntPtr thisptr, ulong steamIdSource);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetFriendFromSourceByIndexCi(
            IntPtr thisptr, ref ulong retarg, ulong steamIdSource, int iFriend);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeIsUserInSourceCc(IntPtr thisptr, ulong steamIdUser, ulong steamIdSource);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetInGameVoiceSpeakingCb(
            IntPtr thisptr, ulong steamIdUser, [MarshalAs(UnmanagedType.I1)] bool bSpeaking);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayS(IntPtr thisptr, string pchDialog);
    };
}