// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamNetworking003VTable
    {
        public IntPtr SendP2PPacket0;
        public IntPtr IsP2PPacketAvailable1;
        public IntPtr ReadP2PPacket2;
        public IntPtr AcceptP2PSessionWithUser3;
        public IntPtr CloseP2PSessionWithUser4;
        public IntPtr GetP2PSessionState5;
        public IntPtr CreateListenSocket6;
        public IntPtr CreateP2PConnectionSocket7;
        public IntPtr CreateConnectionSocket8;
        public IntPtr DestroySocket9;
        public IntPtr DestroyListenSocket10;
        public IntPtr SendDataOnSocket11;
        public IntPtr IsDataAvailableOnSocket12;
        public IntPtr RetrieveDataFromSocket13;
        public IntPtr IsDataAvailable14;
        public IntPtr RetrieveData15;
        public IntPtr GetSocketInfo16;
        public IntPtr GetListenSocketInfo17;
        public IntPtr GetSocketConnectionType18;
        public IntPtr GetMaxPacketSize19;
        private IntPtr DTorISteamNetworking00320;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamNetworking003")]
    public class SteamNetworking003 : InteropHelp.NativeWrapper<SteamNetworking003VTable>
    {
        public bool SendP2PPacket(CSteamId steamIdRemote, byte[] pubData, Ep2PSend eP2PSendType)
        {
            return GetFunction<NativeSendP2PPacketCbue>(Functions.SendP2PPacket0)(ObjectAddress,
                steamIdRemote.ConvertToUint64(), pubData, (uint)pubData.Length, eP2PSendType);
        }

        public bool IsP2PPacketAvailable(ref uint pcubMsgSize)
        {
            return GetFunction<NativeIsP2PPacketAvailableU>(Functions.IsP2PPacketAvailable1)(ObjectAddress,
                ref pcubMsgSize);
        }

        public bool ReadP2PPacket(byte[] pubDest, ref uint pcubMsgSize, ref CSteamId psteamIdRemote)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeReadP2PPacketBuuc>(Functions.ReadP2PPacket2)(ObjectAddress, pubDest,
                (uint)pubDest.Length, ref pcubMsgSize, ref s0);
            psteamIdRemote = new CSteamId(s0);
            return result;
        }

        public bool AcceptP2PSessionWithUser(CSteamId steamIdRemote)
        {
            return GetFunction<NativeAcceptP2PSessionWithUserC>(Functions.AcceptP2PSessionWithUser3)(ObjectAddress,
                steamIdRemote.ConvertToUint64());
        }

        public bool CloseP2PSessionWithUser(CSteamId steamIdRemote)
        {
            return GetFunction<NativeCloseP2PSessionWithUserC>(Functions.CloseP2PSessionWithUser4)(ObjectAddress,
                steamIdRemote.ConvertToUint64());
        }

        public bool GetP2PSessionState(CSteamId steamIdRemote, ref P2PSessionStateT pConnectionState)
        {
            return GetFunction<NativeGetP2PSessionStateCp>(Functions.GetP2PSessionState5)(ObjectAddress,
                steamIdRemote.ConvertToUint64(), ref pConnectionState);
        }

        public uint CreateListenSocket(int nVirtualP2PPort, uint nIp, ushort nPort, bool bAllowUseOfPacketRelay)
        {
            return GetFunction<NativeCreateListenSocketIuub>(Functions.CreateListenSocket6)(ObjectAddress,
                nVirtualP2PPort, nIp, nPort, bAllowUseOfPacketRelay);
        }

        public uint CreateP2PConnectionSocket(CSteamId steamIdTarget, int nVirtualPort, int nTimeoutSec,
            bool bAllowUseOfPacketRelay)
        {
            return GetFunction<NativeCreateP2PConnectionSocketCiib>(Functions.CreateP2PConnectionSocket7)(
                ObjectAddress, steamIdTarget.ConvertToUint64(), nVirtualPort, nTimeoutSec, bAllowUseOfPacketRelay);
        }

        public uint CreateConnectionSocket(uint nIp, ushort nPort, int nTimeoutSec)
        {
            return GetFunction<NativeCreateConnectionSocketUui>(Functions.CreateConnectionSocket8)(ObjectAddress, nIp,
                nPort, nTimeoutSec);
        }

        public bool DestroySocket(uint hSocket, bool bNotifyRemoteEnd)
        {
            return GetFunction<NativeDestroySocketUb>(Functions.DestroySocket9)(ObjectAddress, hSocket, bNotifyRemoteEnd);
        }

        public bool DestroyListenSocket(uint hSocket, bool bNotifyRemoteEnd)
        {
            return GetFunction<NativeDestroyListenSocketUb>(Functions.DestroyListenSocket10)(ObjectAddress, hSocket,
                bNotifyRemoteEnd);
        }

        public bool SendDataOnSocket(uint hSocket, byte[] pubData, bool bReliable)
        {
            return GetFunction<NativeSendDataOnSocketUbub>(Functions.SendDataOnSocket11)(ObjectAddress, hSocket, pubData,
                (uint)pubData.Length, bReliable);
        }

        public bool IsDataAvailableOnSocket(uint hSocket, ref uint pcubMsgSize)
        {
            return GetFunction<NativeIsDataAvailableOnSocketUu>(Functions.IsDataAvailableOnSocket12)(ObjectAddress,
                hSocket, ref pcubMsgSize);
        }

        public bool RetrieveDataFromSocket(uint hSocket, byte[] pubDest, ref uint pcubMsgSize)
        {
            return GetFunction<NativeRetrieveDataFromSocketUbuu>(Functions.RetrieveDataFromSocket13)(ObjectAddress,
                hSocket, pubDest, (uint)pubDest.Length, ref pcubMsgSize);
        }

        public bool IsDataAvailable(uint hListenSocket, ref uint pcubMsgSize, ref uint phSocket)
        {
            return GetFunction<NativeIsDataAvailableUuu>(Functions.IsDataAvailable14)(ObjectAddress, hListenSocket,
                ref pcubMsgSize, ref phSocket);
        }

        public bool RetrieveData(uint hListenSocket, byte[] pubDest, ref uint pcubMsgSize, ref uint phSocket)
        {
            return GetFunction<NativeRetrieveDataUbuuu>(Functions.RetrieveData15)(ObjectAddress, hListenSocket, pubDest,
                (uint)pubDest.Length, ref pcubMsgSize, ref phSocket);
        }

        public bool GetSocketInfo(uint hSocket, ref CSteamId pSteamIdRemote, ref int peSocketStatus,
            ref uint punIpRemote, ref ushort punPortRemote)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetSocketInfoUciuu>(Functions.GetSocketInfo16)(ObjectAddress, hSocket, ref s0,
                ref peSocketStatus, ref punIpRemote, ref punPortRemote);
            pSteamIdRemote = new CSteamId(s0);
            return result;
        }

        public bool GetListenSocketInfo(uint hListenSocket, ref uint pnIp, ref ushort pnPort)
        {
            return GetFunction<NativeGetListenSocketInfoUuu>(Functions.GetListenSocketInfo17)(ObjectAddress,
                hListenSocket, ref pnIp, ref pnPort);
        }

        public EsNetSocketConnectionType GetSocketConnectionType(uint hSocket)
        {
            return GetFunction<NativeGetSocketConnectionTypeU>(Functions.GetSocketConnectionType18)(ObjectAddress,
                hSocket);
        }

        public int GetMaxPacketSize(uint hSocket)
        {
            return GetFunction<NativeGetMaxPacketSizeU>(Functions.GetMaxPacketSize19)(ObjectAddress, hSocket);
        }

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendP2PPacketCbue(
            IntPtr thisptr, ulong steamIdRemote, byte[] pubData, uint cubData, Ep2PSend eP2PSendType);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeIsP2PPacketAvailableU(IntPtr thisptr, ref uint pcubMsgSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeReadP2PPacketBuuc(
            IntPtr thisptr, byte[] pubDest, uint cubDest, ref uint pcubMsgSize, ref ulong psteamIdRemote);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeAcceptP2PSessionWithUserC(IntPtr thisptr, ulong steamIdRemote);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeCloseP2PSessionWithUserC(IntPtr thisptr, ulong steamIdRemote);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetP2PSessionStateCp(
            IntPtr thisptr, ulong steamIdRemote, ref P2PSessionStateT pConnectionState);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeCreateListenSocketIuub(
            IntPtr thisptr, int nVirtualP2PPort, uint nIp, ushort nPort,
            [MarshalAs(UnmanagedType.I1)] bool bAllowUseOfPacketRelay);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeCreateP2PConnectionSocketCiib(
            IntPtr thisptr, ulong steamIdTarget, int nVirtualPort, int nTimeoutSec,
            [MarshalAs(UnmanagedType.I1)] bool bAllowUseOfPacketRelay);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeCreateConnectionSocketUui(IntPtr thisptr, uint nIp, ushort nPort, int nTimeoutSec);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeDestroySocketUb(
            IntPtr thisptr, uint hSocket, [MarshalAs(UnmanagedType.I1)] bool bNotifyRemoteEnd);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeDestroyListenSocketUb(
            IntPtr thisptr, uint hSocket, [MarshalAs(UnmanagedType.I1)] bool bNotifyRemoteEnd);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendDataOnSocketUbub(
            IntPtr thisptr, uint hSocket, byte[] pubData, uint cubData, [MarshalAs(UnmanagedType.I1)] bool bReliable);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeIsDataAvailableOnSocketUu(IntPtr thisptr, uint hSocket, ref uint pcubMsgSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRetrieveDataFromSocketUbuu(
            IntPtr thisptr, uint hSocket, byte[] pubDest, uint cubDest, ref uint pcubMsgSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeIsDataAvailableUuu(
            IntPtr thisptr, uint hListenSocket, ref uint pcubMsgSize, ref uint phSocket);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRetrieveDataUbuuu(
            IntPtr thisptr, uint hListenSocket, byte[] pubDest, uint cubDest, ref uint pcubMsgSize, ref uint phSocket);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetSocketInfoUciuu(
            IntPtr thisptr, uint hSocket, ref ulong pSteamIdRemote, ref int peSocketStatus, ref uint punIpRemote,
            ref ushort punPortRemote);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetListenSocketInfoUuu(
            IntPtr thisptr, uint hListenSocket, ref uint pnIp, ref ushort pnPort);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EsNetSocketConnectionType NativeGetSocketConnectionTypeU(IntPtr thisptr, uint hSocket);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetMaxPacketSizeU(IntPtr thisptr, uint hSocket);
    };
}