// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamContentServer001VTable
    {
        public IntPtr LogOn0;
        public IntPtr LogOff1;
        public IntPtr BLoggedOn2;
        public IntPtr SendClientContentAuthRequest3;
        private IntPtr DTorISteamContentServer0014;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamContentServer001")]
    public class SteamContentServer001 : InteropHelp.NativeWrapper<SteamContentServer001VTable>
    {
        public bool LogOn(uint uContentServerId)
        {
            return GetFunction<NativeLogOnU>(Functions.LogOn0)(ObjectAddress, uContentServerId);
        }

        public bool LogOff()
        {
            return GetFunction<NativeLogOff>(Functions.LogOff1)(ObjectAddress);
        }

        public bool BLoggedOn()
        {
            return GetFunction<NativeBLoggedOn>(Functions.BLoggedOn2)(ObjectAddress);
        }

        public void SendClientContentAuthRequest(CSteamId steamId, uint unContentId)
        {
            GetFunction<NativeSendClientContentAuthRequestCu>(Functions.SendClientContentAuthRequest3)(ObjectAddress,
                steamId.ConvertToUint64(), unContentId);
        }

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeLogOnU(IntPtr thisptr, uint uContentServerId);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeLogOff(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeBLoggedOn(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSendClientContentAuthRequestCu(IntPtr thisptr, ulong steamId, uint unContentId);
    };
}