// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamFriends006VTable
    {
        public IntPtr GetPersonaName0;
        public IntPtr SetPersonaName1;
        public IntPtr GetPersonaState2;
        public IntPtr GetFriendCount3;
        public IntPtr GetFriendByIndex4;
        public IntPtr GetFriendRelationship5;
        public IntPtr GetFriendPersonaState6;
        public IntPtr GetFriendPersonaName7;
        public IntPtr GetFriendAvatar8;
        public IntPtr GetFriendGamePlayed9;
        public IntPtr GetFriendPersonaNameHistory10;
        public IntPtr HasFriend11;
        public IntPtr GetClanCount12;
        public IntPtr GetClanByIndex13;
        public IntPtr GetClanName14;
        public IntPtr GetClanTag15;
        public IntPtr GetFriendCountFromSource16;
        public IntPtr GetFriendFromSourceByIndex17;
        public IntPtr IsUserInSource18;
        public IntPtr SetInGameVoiceSpeaking19;
        public IntPtr ActivateGameOverlay20;
        public IntPtr ActivateGameOverlayToUser21;
        public IntPtr ActivateGameOverlayToWebPage22;
        public IntPtr ActivateGameOverlayToStore23;
        public IntPtr SetPlayedWith24;
        public IntPtr ActivateGameOverlayInviteDialog25;
        private IntPtr DTorISteamFriends00626;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamFriends006")]
    public class SteamFriends006 : InteropHelp.NativeWrapper<SteamFriends006VTable>
    {
        public string GetPersonaName()
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetPersonaName>(Functions.GetPersonaName0)(ObjectAddress)));
        }

        public void SetPersonaName(string pchPersonaName)
        {
            GetFunction<NativeSetPersonaNameS>(Functions.SetPersonaName1)(ObjectAddress, pchPersonaName);
        }

        public EPersonaState GetPersonaState()
        {
            return GetFunction<NativeGetPersonaState>(Functions.GetPersonaState2)(ObjectAddress);
        }

        public int GetFriendCount(EFriendFlags eFriendFlags)
        {
            return GetFunction<NativeGetFriendCountE>(Functions.GetFriendCount3)(ObjectAddress, eFriendFlags);
        }

        public CSteamId GetFriendByIndex(int iFriend, int iFriendFlags)
        {
            ulong ret = 0;
            GetFunction<NativeGetFriendByIndexIi>(Functions.GetFriendByIndex4)(ObjectAddress, ref ret, iFriend,
                iFriendFlags);
            return new CSteamId(ret);
        }

        public EFriendRelationship GetFriendRelationship(CSteamId steamIdFriend)
        {
            return GetFunction<NativeGetFriendRelationshipC>(Functions.GetFriendRelationship5)(ObjectAddress,
                steamIdFriend.ConvertToUint64());
        }

        public EPersonaState GetFriendPersonaState(CSteamId steamIdFriend)
        {
            return GetFunction<NativeGetFriendPersonaStateC>(Functions.GetFriendPersonaState6)(ObjectAddress,
                steamIdFriend.ConvertToUint64());
        }

        public string GetFriendPersonaName(CSteamId steamIdFriend)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetFriendPersonaNameC>(Functions.GetFriendPersonaName7)(ObjectAddress,
                            steamIdFriend.ConvertToUint64())));
        }

        public int GetFriendAvatar(CSteamId steamIdFriend, int eAvatarSize)
        {
            return GetFunction<NativeGetFriendAvatarCi>(Functions.GetFriendAvatar8)(ObjectAddress,
                steamIdFriend.ConvertToUint64(), eAvatarSize);
        }

        public bool GetFriendGamePlayed(CSteamId steamIdFriend, ref FriendGameInfoT pFriendGameInfo)
        {
            return GetFunction<NativeGetFriendGamePlayedCf>(Functions.GetFriendGamePlayed9)(ObjectAddress,
                steamIdFriend.ConvertToUint64(), ref pFriendGameInfo);
        }

        public string GetFriendPersonaNameHistory(CSteamId steamIdFriend, int iPersonaName)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetFriendPersonaNameHistoryCi>(Functions.GetFriendPersonaNameHistory10)(
                            ObjectAddress, steamIdFriend.ConvertToUint64(), iPersonaName)));
        }

        public bool HasFriend(CSteamId steamIdFriend, EFriendFlags eFriendFlags)
        {
            return GetFunction<NativeHasFriendCe>(Functions.HasFriend11)(ObjectAddress, steamIdFriend.ConvertToUint64(),
                eFriendFlags);
        }

        public int GetClanCount()
        {
            return GetFunction<NativeGetClanCount>(Functions.GetClanCount12)(ObjectAddress);
        }

        public CSteamId GetClanByIndex(int iClan)
        {
            ulong ret = 0;
            GetFunction<NativeGetClanByIndexI>(Functions.GetClanByIndex13)(ObjectAddress, ref ret, iClan);
            return new CSteamId(ret);
        }

        public string GetClanName(CSteamId steamIdClan)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetClanNameC>(Functions.GetClanName14)(ObjectAddress,
                        steamIdClan.ConvertToUint64())));
        }

        public string GetClanTag(CSteamId steamIdClan)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetClanTagC>(Functions.GetClanTag15)(ObjectAddress,
                        steamIdClan.ConvertToUint64())));
        }

        public int GetFriendCountFromSource(CSteamId steamIdSource)
        {
            return GetFunction<NativeGetFriendCountFromSourceC>(Functions.GetFriendCountFromSource16)(ObjectAddress,
                steamIdSource.ConvertToUint64());
        }

        public CSteamId GetFriendFromSourceByIndex(CSteamId steamIdSource, int iFriend)
        {
            ulong ret = 0;
            GetFunction<NativeGetFriendFromSourceByIndexCi>(Functions.GetFriendFromSourceByIndex17)(ObjectAddress,
                ref ret, steamIdSource.ConvertToUint64(), iFriend);
            return new CSteamId(ret);
        }

        public bool IsUserInSource(CSteamId steamIdUser, CSteamId steamIdSource)
        {
            return GetFunction<NativeIsUserInSourceCc>(Functions.IsUserInSource18)(ObjectAddress,
                steamIdUser.ConvertToUint64(), steamIdSource.ConvertToUint64());
        }

        public void SetInGameVoiceSpeaking(CSteamId steamIdUser, bool bSpeaking)
        {
            GetFunction<NativeSetInGameVoiceSpeakingCb>(Functions.SetInGameVoiceSpeaking19)(ObjectAddress,
                steamIdUser.ConvertToUint64(), bSpeaking);
        }

        public void ActivateGameOverlay(string pchDialog)
        {
            GetFunction<NativeActivateGameOverlayS>(Functions.ActivateGameOverlay20)(ObjectAddress, pchDialog);
        }

        public void ActivateGameOverlayToUser(string pchDialog, CSteamId steamId)
        {
            GetFunction<NativeActivateGameOverlayToUserSc>(Functions.ActivateGameOverlayToUser21)(ObjectAddress,
                pchDialog, steamId.ConvertToUint64());
        }

        public void ActivateGameOverlayToWebPage(string pchUrl)
        {
            GetFunction<NativeActivateGameOverlayToWebPageS>(Functions.ActivateGameOverlayToWebPage22)(ObjectAddress,
                pchUrl);
        }

        public void ActivateGameOverlayToStore(uint nAppId)
        {
            GetFunction<NativeActivateGameOverlayToStoreU>(Functions.ActivateGameOverlayToStore23)(ObjectAddress, nAppId);
        }

        public void SetPlayedWith(CSteamId steamIdUserPlayedWith)
        {
            GetFunction<NativeSetPlayedWithC>(Functions.SetPlayedWith24)(ObjectAddress,
                steamIdUserPlayedWith.ConvertToUint64());
        }

        public void ActivateGameOverlayInviteDialog(CSteamId steamIdLobby)
        {
            GetFunction<NativeActivateGameOverlayInviteDialogC>(Functions.ActivateGameOverlayInviteDialog25)(
                ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetPersonaName(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetPersonaNameS(IntPtr thisptr, string pchPersonaName);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EPersonaState NativeGetPersonaState(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendCountE(IntPtr thisptr, EFriendFlags eFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetFriendByIndexIi(IntPtr thisptr, ref ulong retarg, int iFriend, int iFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EFriendRelationship NativeGetFriendRelationshipC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EPersonaState NativeGetFriendPersonaStateC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetFriendPersonaNameC(IntPtr thisptr, ulong steamIdFriend);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendAvatarCi(IntPtr thisptr, ulong steamIdFriend, int eAvatarSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFriendGamePlayedCf(
            IntPtr thisptr, ulong steamIdFriend, ref FriendGameInfoT pFriendGameInfo);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetFriendPersonaNameHistoryCi(
            IntPtr thisptr, ulong steamIdFriend, int iPersonaName);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeHasFriendCe(IntPtr thisptr, ulong steamIdFriend, EFriendFlags eFriendFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetClanCount(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetClanByIndexI(IntPtr thisptr, ref ulong retarg, int iClan);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetClanNameC(IntPtr thisptr, ulong steamIdClan);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetClanTagC(IntPtr thisptr, ulong steamIdClan);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFriendCountFromSourceC(IntPtr thisptr, ulong steamIdSource);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetFriendFromSourceByIndexCi(
            IntPtr thisptr, ref ulong retarg, ulong steamIdSource, int iFriend);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeIsUserInSourceCc(IntPtr thisptr, ulong steamIdUser, ulong steamIdSource);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetInGameVoiceSpeakingCb(
            IntPtr thisptr, ulong steamIdUser, [MarshalAs(UnmanagedType.I1)] bool bSpeaking);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayS(IntPtr thisptr, string pchDialog);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayToUserSc(IntPtr thisptr, string pchDialog, ulong steamId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayToWebPageS(IntPtr thisptr, string pchUrl);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayToStoreU(IntPtr thisptr, uint nAppId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetPlayedWithC(IntPtr thisptr, ulong steamIdUserPlayedWith);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeActivateGameOverlayInviteDialogC(IntPtr thisptr, ulong steamIdLobby);
    };
}