// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmaking006VTable
    {
        public IntPtr GetFavoriteGameCount0;
        public IntPtr GetFavoriteGame1;
        public IntPtr AddFavoriteGame2;
        public IntPtr RemoveFavoriteGame3;
        public IntPtr RequestLobbyList4;
        public IntPtr AddRequestLobbyListFilter5;
        public IntPtr AddRequestLobbyListNumericalFilter6;
        public IntPtr AddRequestLobbyListNearValueFilter7;
        public IntPtr GetLobbyByIndex8;
        public IntPtr CreateLobby9;
        public IntPtr JoinLobby10;
        public IntPtr LeaveLobby11;
        public IntPtr InviteUserToLobby12;
        public IntPtr GetNumLobbyMembers13;
        public IntPtr GetLobbyMemberByIndex14;
        public IntPtr GetLobbyData15;
        public IntPtr SetLobbyData16;
        public IntPtr GetLobbyMemberData17;
        public IntPtr SetLobbyMemberData18;
        public IntPtr SendLobbyChatMsg19;
        public IntPtr GetLobbyChatEntry20;
        public IntPtr RequestLobbyData21;
        public IntPtr SetLobbyGameServer22;
        public IntPtr GetLobbyGameServer23;
        public IntPtr SetLobbyMemberLimit24;
        public IntPtr GetLobbyMemberLimit25;
        public IntPtr SetLobbyType26;
        public IntPtr GetLobbyOwner27;
        private IntPtr DTorISteamMatchmaking00628;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamMatchMaking006")]
    public class SteamMatchmaking006 : InteropHelp.NativeWrapper<SteamMatchmaking006VTable>
    {
        public int GetFavoriteGameCount()
        {
            return GetFunction<NativeGetFavoriteGameCount>(Functions.GetFavoriteGameCount0)(ObjectAddress);
        }

        public bool GetFavoriteGame(int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort,
            ref ushort pnQueryPort, ref uint punFlags, ref uint pRTime32LastPlayedOnServer)
        {
            return GetFunction<NativeGetFavoriteGameIuuuuuu>(Functions.GetFavoriteGame1)(ObjectAddress, iGame,
                ref pnAppId, ref pnIp, ref pnConnPort, ref pnQueryPort, ref punFlags, ref pRTime32LastPlayedOnServer);
        }

        public int AddFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer)
        {
            return GetFunction<NativeAddFavoriteGameUuuuuu>(Functions.AddFavoriteGame2)(ObjectAddress, nAppId, nIp,
                nConnPort, nQueryPort, unFlags, rTime32LastPlayedOnServer);
        }

        public bool RemoveFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags)
        {
            return GetFunction<NativeRemoveFavoriteGameUuuuu>(Functions.RemoveFavoriteGame3)(ObjectAddress, nAppId, nIp,
                nConnPort, nQueryPort, unFlags);
        }

        public ulong RequestLobbyList()
        {
            return GetFunction<NativeRequestLobbyList>(Functions.RequestLobbyList4)(ObjectAddress);
        }

        public void AddRequestLobbyListFilter(string pchKeyToMatch, string pchValueToMatch)
        {
            GetFunction<NativeAddRequestLobbyListFilterSs>(Functions.AddRequestLobbyListFilter5)(ObjectAddress,
                pchKeyToMatch, pchValueToMatch);
        }

        public void AddRequestLobbyListNumericalFilter(string pchKeyToMatch, int nValueToMatch, int nComparisonType)
        {
            GetFunction<NativeAddRequestLobbyListNumericalFilterSii>(Functions.AddRequestLobbyListNumericalFilter6)(
                ObjectAddress, pchKeyToMatch, nValueToMatch, nComparisonType);
        }

        public void AddRequestLobbyListNearValueFilter(string pchKeyToMatch, int nValueToBeCloseTo)
        {
            GetFunction<NativeAddRequestLobbyListNearValueFilterSi>(Functions.AddRequestLobbyListNearValueFilter7)(
                ObjectAddress, pchKeyToMatch, nValueToBeCloseTo);
        }

        public CSteamId GetLobbyByIndex(int iLobby)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyByIndexI>(Functions.GetLobbyByIndex8)(ObjectAddress, ref ret, iLobby);
            return new CSteamId(ret);
        }

        public ulong CreateLobby(ELobbyType eLobbyType)
        {
            return GetFunction<NativeCreateLobbyE>(Functions.CreateLobby9)(ObjectAddress, eLobbyType);
        }

        public ulong JoinLobby(CSteamId steamIdLobby)
        {
            return GetFunction<NativeJoinLobbyC>(Functions.JoinLobby10)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public void LeaveLobby(CSteamId steamIdLobby)
        {
            GetFunction<NativeLeaveLobbyC>(Functions.LeaveLobby11)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public bool InviteUserToLobby(CSteamId steamIdLobby, CSteamId steamIdInvitee)
        {
            return GetFunction<NativeInviteUserToLobbyCc>(Functions.InviteUserToLobby12)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdInvitee.ConvertToUint64());
        }

        public int GetNumLobbyMembers(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetNumLobbyMembersC>(Functions.GetNumLobbyMembers13)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public CSteamId GetLobbyMemberByIndex(CSteamId steamIdLobby, int iMember)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyMemberByIndexCi>(Functions.GetLobbyMemberByIndex14)(ObjectAddress, ref ret,
                steamIdLobby.ConvertToUint64(), iMember);
            return new CSteamId(ret);
        }

        public string GetLobbyData(CSteamId steamIdLobby, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetLobbyDataCs>(Functions.GetLobbyData15)(ObjectAddress,
                        steamIdLobby.ConvertToUint64(), pchKey)));
        }

        public bool SetLobbyData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            return GetFunction<NativeSetLobbyDataCss>(Functions.SetLobbyData16)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey, pchValue);
        }

        public string GetLobbyMemberData(CSteamId steamIdLobby, CSteamId steamIdUser, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetLobbyMemberDataCcs>(Functions.GetLobbyMemberData17)(ObjectAddress,
                            steamIdLobby.ConvertToUint64(), steamIdUser.ConvertToUint64(), pchKey)));
        }

        public void SetLobbyMemberData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            GetFunction<NativeSetLobbyMemberDataCss>(Functions.SetLobbyMemberData18)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey, pchValue);
        }

        public bool SendLobbyChatMsg(CSteamId steamIdLobby, byte[] pvMsgBody)
        {
            return GetFunction<NativeSendLobbyChatMsgCbi>(Functions.SendLobbyChatMsg19)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pvMsgBody, pvMsgBody.Length);
        }

        public int GetLobbyChatEntry(CSteamId steamIdLobby, int iChatId, ref CSteamId pSteamIdUser, byte[] pvData,
            ref EChatEntryType peChatEntryType)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetLobbyChatEntryCicbie>(Functions.GetLobbyChatEntry20)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), iChatId, ref s0, pvData, pvData.Length, ref peChatEntryType);
            pSteamIdUser = new CSteamId(s0);
            return result;
        }

        public bool RequestLobbyData(CSteamId steamIdLobby)
        {
            return GetFunction<NativeRequestLobbyDataC>(Functions.RequestLobbyData21)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public void SetLobbyGameServer(CSteamId steamIdLobby, uint unGameServerIp, ushort unGameServerPort,
            CSteamId steamIdGameServer)
        {
            GetFunction<NativeSetLobbyGameServerCuuc>(Functions.SetLobbyGameServer22)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), unGameServerIp, unGameServerPort, steamIdGameServer.ConvertToUint64());
        }

        public bool GetLobbyGameServer(CSteamId steamIdLobby, ref uint punGameServerIp, ref ushort punGameServerPort,
            ref CSteamId psteamIdGameServer)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetLobbyGameServerCuuc>(Functions.GetLobbyGameServer23)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), ref punGameServerIp, ref punGameServerPort, ref s0);
            psteamIdGameServer = new CSteamId(s0);
            return result;
        }

        public bool SetLobbyMemberLimit(CSteamId steamIdLobby, int cMaxMembers)
        {
            return GetFunction<NativeSetLobbyMemberLimitCi>(Functions.SetLobbyMemberLimit24)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), cMaxMembers);
        }

        public int GetLobbyMemberLimit(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetLobbyMemberLimitC>(Functions.GetLobbyMemberLimit25)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public bool SetLobbyType(CSteamId steamIdLobby, ELobbyType eLobbyType)
        {
            return GetFunction<NativeSetLobbyTypeCe>(Functions.SetLobbyType26)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), eLobbyType);
        }

        public CSteamId GetLobbyOwner(CSteamId steamIdLobby)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyOwnerC>(Functions.GetLobbyOwner27)(ObjectAddress, ref ret,
                steamIdLobby.ConvertToUint64());
            return new CSteamId(ret);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFavoriteGameCount(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFavoriteGameIuuuuuu(
            IntPtr thisptr, int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort, ref ushort pnQueryPort,
            ref uint punFlags, ref uint pRTime32LastPlayedOnServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeAddFavoriteGameUuuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRemoveFavoriteGameUuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeRequestLobbyList(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListFilterSs(
            IntPtr thisptr, string pchKeyToMatch, string pchValueToMatch);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListNumericalFilterSii(
            IntPtr thisptr, string pchKeyToMatch, int nValueToMatch, int nComparisonType);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddRequestLobbyListNearValueFilterSi(
            IntPtr thisptr, string pchKeyToMatch, int nValueToBeCloseTo);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyByIndexI(IntPtr thisptr, ref ulong retarg, int iLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeCreateLobbyE(IntPtr thisptr, ELobbyType eLobbyType);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ulong NativeJoinLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeLeaveLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeInviteUserToLobbyCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdInvitee);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetNumLobbyMembersC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyMemberByIndexCi(
            IntPtr thisptr, ref ulong retarg, ulong steamIdLobby, int iMember);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyDataCs(IntPtr thisptr, ulong steamIdLobby, string pchKey);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyDataCss(IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyMemberDataCcs(
            IntPtr thisptr, ulong steamIdLobby, ulong steamIdUser, string pchKey);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyMemberDataCss(
            IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendLobbyChatMsgCbi(
            IntPtr thisptr, ulong steamIdLobby, byte[] pvMsgBody, int cubMsgBody);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyChatEntryCicbie(
            IntPtr thisptr, ulong steamIdLobby, int iChatId, ref ulong pSteamIdUser, byte[] pvData, int cubData,
            ref EChatEntryType peChatEntryType);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRequestLobbyDataC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyGameServerCuuc(
            IntPtr thisptr, ulong steamIdLobby, uint unGameServerIp, ushort unGameServerPort, ulong steamIdGameServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetLobbyGameServerCuuc(
            IntPtr thisptr, ulong steamIdLobby, ref uint punGameServerIp, ref ushort punGameServerPort,
            ref ulong psteamIdGameServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyMemberLimitCi(IntPtr thisptr, ulong steamIdLobby, int cMaxMembers);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyMemberLimitC(IntPtr thisptr, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetLobbyTypeCe(IntPtr thisptr, ulong steamIdLobby, ELobbyType eLobbyType);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyOwnerC(IntPtr thisptr, ref ulong retarg, ulong steamIdLobby);
    };
}