// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamHttp001VTable
    {
        public IntPtr CreateHTTPRequest0;
        public IntPtr SetHTTPRequestContextValue1;
        public IntPtr SetHTTPRequestNetworkActivityTimeout2;
        public IntPtr SetHTTPRequestHeaderValue3;
        public IntPtr SetHTTPRequestGetOrPostParameter4;
        public IntPtr SendHTTPRequest5;
        public IntPtr DeferHTTPRequest6;
        public IntPtr PrioritizeHTTPRequest7;
        public IntPtr GetHTTPResponseHeaderSize8;
        public IntPtr GetHTTPResponseHeaderValue9;
        public IntPtr GetHTTPResponseBodySize10;
        public IntPtr GetHTTPResponseBodyData11;
        public IntPtr ReleaseHTTPRequest12;
        public IntPtr GetHTTPDownloadProgressPct13;
        public IntPtr SetHTTPRequestRawPostBody14;
        private IntPtr DTorISteamHTTP00115;
    };

    [InteropHelp.InterfaceVersionAttribute("STEAMHTTP_INTERFACE_VERSION001")]
    public class SteamHttp001 : InteropHelp.NativeWrapper<SteamHttp001VTable>
    {
        public uint CreateHttpRequest(EhttpMethod eHttpRequestMethod, string pchAbsoluteUrl)
        {
            return GetFunction<NativeCreateHttpRequestEs>(Functions.CreateHTTPRequest0)(ObjectAddress,
                eHttpRequestMethod, pchAbsoluteUrl);
        }

        public bool SetHttpRequestContextValue(uint hRequest, ulong ulContextValue)
        {
            return GetFunction<NativeSetHttpRequestContextValueUu>(Functions.SetHTTPRequestContextValue1)(
                ObjectAddress, hRequest, ulContextValue);
        }

        public bool SetHttpRequestNetworkActivityTimeout(uint hRequest, uint unTimeoutSeconds)
        {
            return
                GetFunction<NativeSetHttpRequestNetworkActivityTimeoutUu>(
                    Functions.SetHTTPRequestNetworkActivityTimeout2)(ObjectAddress, hRequest, unTimeoutSeconds);
        }

        public bool SetHttpRequestHeaderValue(uint hRequest, string pchHeaderName, string pchHeaderValue)
        {
            return GetFunction<NativeSetHttpRequestHeaderValueUss>(Functions.SetHTTPRequestHeaderValue3)(ObjectAddress,
                hRequest, pchHeaderName, pchHeaderValue);
        }

        public bool SetHttpRequestGetOrPostParameter(uint hRequest, string pchParamName, string pchParamValue)
        {
            return
                GetFunction<NativeSetHttpRequestGetOrPostParameterUss>(Functions.SetHTTPRequestGetOrPostParameter4)(
                    ObjectAddress, hRequest, pchParamName, pchParamValue);
        }

        public bool SendHttpRequest(uint hRequest, ref ulong pCallHandle)
        {
            return GetFunction<NativeSendHttpRequestUu>(Functions.SendHTTPRequest5)(ObjectAddress, hRequest,
                ref pCallHandle);
        }

        public bool DeferHttpRequest(uint hRequest)
        {
            return GetFunction<NativeDeferHttpRequestU>(Functions.DeferHTTPRequest6)(ObjectAddress, hRequest);
        }

        public bool PrioritizeHttpRequest(uint hRequest)
        {
            return GetFunction<NativePrioritizeHttpRequestU>(Functions.PrioritizeHTTPRequest7)(ObjectAddress, hRequest);
        }

        public bool GetHttpResponseHeaderSize(uint hRequest, string pchHeaderName, ref uint unResponseHeaderSize)
        {
            return GetFunction<NativeGetHttpResponseHeaderSizeUsu>(Functions.GetHTTPResponseHeaderSize8)(ObjectAddress,
                hRequest, pchHeaderName, ref unResponseHeaderSize);
        }

        public bool GetHttpResponseHeaderValue(uint hRequest, string pchHeaderName, byte[] pHeaderValueBuffer)
        {
            return
                GetFunction<NativeGetHttpResponseHeaderValueUsbu>(Functions.GetHTTPResponseHeaderValue9)(ObjectAddress,
                    hRequest, pchHeaderName, pHeaderValueBuffer, (uint)pHeaderValueBuffer.Length);
        }

        public bool GetHttpResponseBodySize(uint hRequest, ref uint unBodySize)
        {
            return GetFunction<NativeGetHttpResponseBodySizeUu>(Functions.GetHTTPResponseBodySize10)(ObjectAddress,
                hRequest, ref unBodySize);
        }

        public bool GetHttpResponseBodyData(uint hRequest, byte[] pBodyDataBuffer)
        {
            return GetFunction<NativeGetHttpResponseBodyDataUbu>(Functions.GetHTTPResponseBodyData11)(ObjectAddress,
                hRequest, pBodyDataBuffer, (uint)pBodyDataBuffer.Length);
        }

        public bool ReleaseHttpRequest(uint hRequest)
        {
            return GetFunction<NativeReleaseHttpRequestU>(Functions.ReleaseHTTPRequest12)(ObjectAddress, hRequest);
        }

        public bool GetHttpDownloadProgressPct(uint hRequest, ref float pflPercentOut)
        {
            return GetFunction<NativeGetHttpDownloadProgressPctUf>(Functions.GetHTTPDownloadProgressPct13)(
                ObjectAddress, hRequest, ref pflPercentOut);
        }

        public bool SetHttpRequestRawPostBody(uint hRequest, string pchContentType, byte[] pubBody)
        {
            return GetFunction<NativeSetHttpRequestRawPostBodyUsbu>(Functions.SetHTTPRequestRawPostBody14)(
                ObjectAddress, hRequest, pchContentType, pubBody, (uint)pubBody.Length);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeCreateHttpRequestEs(
            IntPtr thisptr, EhttpMethod eHttpRequestMethod, string pchAbsoluteUrl);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetHttpRequestContextValueUu(IntPtr thisptr, uint hRequest, ulong ulContextValue);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetHttpRequestNetworkActivityTimeoutUu(
            IntPtr thisptr, uint hRequest, uint unTimeoutSeconds);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetHttpRequestHeaderValueUss(
            IntPtr thisptr, uint hRequest, string pchHeaderName, string pchHeaderValue);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetHttpRequestGetOrPostParameterUss(
            IntPtr thisptr, uint hRequest, string pchParamName, string pchParamValue);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendHttpRequestUu(IntPtr thisptr, uint hRequest, ref ulong pCallHandle);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeDeferHttpRequestU(IntPtr thisptr, uint hRequest);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativePrioritizeHttpRequestU(IntPtr thisptr, uint hRequest);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetHttpResponseHeaderSizeUsu(
            IntPtr thisptr, uint hRequest, string pchHeaderName, ref uint unResponseHeaderSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetHttpResponseHeaderValueUsbu(
            IntPtr thisptr, uint hRequest, string pchHeaderName, byte[] pHeaderValueBuffer, uint unBufferSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetHttpResponseBodySizeUu(IntPtr thisptr, uint hRequest, ref uint unBodySize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetHttpResponseBodyDataUbu(
            IntPtr thisptr, uint hRequest, byte[] pBodyDataBuffer, uint unBufferSize);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeReleaseHttpRequestU(IntPtr thisptr, uint hRequest);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetHttpDownloadProgressPctUf(IntPtr thisptr, uint hRequest, ref float pflPercentOut);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetHttpRequestRawPostBodyUsbu(
            IntPtr thisptr, uint hRequest, string pchContentType, byte[] pubBody, uint unBodyLen);
    };
}