// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmaking001VTable
    {
        public IntPtr GetFavoriteGameCount0;
        public IntPtr GetFavoriteGame1;
        public IntPtr AddFavoriteGame2;
        public IntPtr RemoveFavoriteGame3;
        public IntPtr GetFavoriteGame24;
        public IntPtr AddFavoriteGame25;
        public IntPtr RemoveFavoriteGame26;
        public IntPtr RequestLobbyList7;
        public IntPtr GetLobbyByIndex8;
        public IntPtr CreateLobby9;
        public IntPtr JoinLobby10;
        public IntPtr LeaveLobby11;
        public IntPtr InviteUserToLobby12;
        public IntPtr GetNumLobbyMembers13;
        public IntPtr GetLobbyMemberByIndex14;
        public IntPtr GetLobbyData15;
        public IntPtr SetLobbyData16;
        public IntPtr GetLobbyMemberData17;
        public IntPtr SetLobbyMemberData18;
        public IntPtr ChangeLobbyAdmin19;
        public IntPtr SendLobbyChatMsg20;
        public IntPtr GetLobbyChatEntry21;
        public IntPtr RequestLobbyData22;
        private IntPtr DTorISteamMatchmaking00123;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamMatchMaking001")]
    public class SteamMatchmaking001 : InteropHelp.NativeWrapper<SteamMatchmaking001VTable>
    {
        public int GetFavoriteGameCount()
        {
            return GetFunction<NativeGetFavoriteGameCount>(Functions.GetFavoriteGameCount0)(ObjectAddress);
        }

        public bool GetFavoriteGame(int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort, ref uint punFlags,
            ref uint pRTime32LastPlayedOnServer)
        {
            return GetFunction<NativeGetFavoriteGameIuuuuu>(Functions.GetFavoriteGame1)(ObjectAddress, iGame,
                ref pnAppId, ref pnIp, ref pnConnPort, ref punFlags, ref pRTime32LastPlayedOnServer);
        }

        public int AddFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, uint unFlags, uint rTime32LastPlayedOnServer)
        {
            return GetFunction<NativeAddFavoriteGameUuuuu>(Functions.AddFavoriteGame2)(ObjectAddress, nAppId, nIp,
                nConnPort, unFlags, rTime32LastPlayedOnServer);
        }

        public bool RemoveFavoriteGame(uint nAppId, uint nIp, ushort nConnPort, uint unFlags)
        {
            return GetFunction<NativeRemoveFavoriteGameUuuu>(Functions.RemoveFavoriteGame3)(ObjectAddress, nAppId, nIp,
                nConnPort, unFlags);
        }

        public bool GetFavoriteGame2(int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort,
            ref ushort pnQueryPort, ref uint punFlags, ref uint pRTime32LastPlayedOnServer)
        {
            return GetFunction<NativeGetFavoriteGame2Iuuuuuu>(Functions.GetFavoriteGame24)(ObjectAddress, iGame,
                ref pnAppId, ref pnIp, ref pnConnPort, ref pnQueryPort, ref punFlags, ref pRTime32LastPlayedOnServer);
        }

        public int AddFavoriteGame2(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer)
        {
            return GetFunction<NativeAddFavoriteGame2Uuuuuu>(Functions.AddFavoriteGame25)(ObjectAddress, nAppId, nIp,
                nConnPort, nQueryPort, unFlags, rTime32LastPlayedOnServer);
        }

        public bool RemoveFavoriteGame2(uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags)
        {
            return GetFunction<NativeRemoveFavoriteGame2Uuuuu>(Functions.RemoveFavoriteGame26)(ObjectAddress, nAppId,
                nIp, nConnPort, nQueryPort, unFlags);
        }

        public void RequestLobbyList(ulong ulGameId, ref MatchMakingKeyValuePairT pFilters, uint nFilters)
        {
            GetFunction<NativeRequestLobbyListUmu>(Functions.RequestLobbyList7)(ObjectAddress, ulGameId, ref pFilters,
                nFilters);
        }

        public CSteamId GetLobbyByIndex(int iLobby)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyByIndexI>(Functions.GetLobbyByIndex8)(ObjectAddress, ref ret, iLobby);
            return new CSteamId(ret);
        }

        public void CreateLobby(ulong ulGameId, bool bPrivate)
        {
            GetFunction<NativeCreateLobbyUb>(Functions.CreateLobby9)(ObjectAddress, ulGameId, bPrivate);
        }

        public void JoinLobby(CSteamId steamIdLobby)
        {
            GetFunction<NativeJoinLobbyC>(Functions.JoinLobby10)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public void LeaveLobby(CSteamId steamIdLobby)
        {
            GetFunction<NativeLeaveLobbyC>(Functions.LeaveLobby11)(ObjectAddress, steamIdLobby.ConvertToUint64());
        }

        public bool InviteUserToLobby(CSteamId steamIdLobby, CSteamId steamIdInvitee)
        {
            return GetFunction<NativeInviteUserToLobbyCc>(Functions.InviteUserToLobby12)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdInvitee.ConvertToUint64());
        }

        public int GetNumLobbyMembers(CSteamId steamIdLobby)
        {
            return GetFunction<NativeGetNumLobbyMembersC>(Functions.GetNumLobbyMembers13)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        public CSteamId GetLobbyMemberByIndex(CSteamId steamIdLobby, int iMember)
        {
            ulong ret = 0;
            GetFunction<NativeGetLobbyMemberByIndexCi>(Functions.GetLobbyMemberByIndex14)(ObjectAddress, ref ret,
                steamIdLobby.ConvertToUint64(), iMember);
            return new CSteamId(ret);
        }

        public string GetLobbyData(CSteamId steamIdLobby, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetLobbyDataCs>(Functions.GetLobbyData15)(ObjectAddress,
                        steamIdLobby.ConvertToUint64(), pchKey)));
        }

        public void SetLobbyData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            GetFunction<NativeSetLobbyDataCss>(Functions.SetLobbyData16)(ObjectAddress, steamIdLobby.ConvertToUint64(),
                pchKey, pchValue);
        }

        public string GetLobbyMemberData(CSteamId steamIdLobby, CSteamId steamIdUser, string pchKey)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetLobbyMemberDataCcs>(Functions.GetLobbyMemberData17)(ObjectAddress,
                            steamIdLobby.ConvertToUint64(), steamIdUser.ConvertToUint64(), pchKey)));
        }

        public void SetLobbyMemberData(CSteamId steamIdLobby, string pchKey, string pchValue)
        {
            GetFunction<NativeSetLobbyMemberDataCss>(Functions.SetLobbyMemberData18)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pchKey, pchValue);
        }

        public void ChangeLobbyAdmin(CSteamId steamIdLobby, CSteamId steamIdNewAdmin)
        {
            GetFunction<NativeChangeLobbyAdminCc>(Functions.ChangeLobbyAdmin19)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), steamIdNewAdmin.ConvertToUint64());
        }

        public bool SendLobbyChatMsg(CSteamId steamIdLobby, byte[] pvMsgBody)
        {
            return GetFunction<NativeSendLobbyChatMsgCbi>(Functions.SendLobbyChatMsg20)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), pvMsgBody, pvMsgBody.Length);
        }

        public int GetLobbyChatEntry(CSteamId steamIdLobby, int iChatId, ref CSteamId pSteamIdUser, byte[] pvData,
            ref EChatEntryType peChatEntryType)
        {
            ulong s0 = 0;
            var result = GetFunction<NativeGetLobbyChatEntryCicbie>(Functions.GetLobbyChatEntry21)(ObjectAddress,
                steamIdLobby.ConvertToUint64(), iChatId, ref s0, pvData, pvData.Length, ref peChatEntryType);
            pSteamIdUser = new CSteamId(s0);
            return result;
        }

        public bool RequestLobbyData(CSteamId steamIdLobby)
        {
            return GetFunction<NativeRequestLobbyDataC>(Functions.RequestLobbyData22)(ObjectAddress,
                steamIdLobby.ConvertToUint64());
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetFavoriteGameCount(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFavoriteGameIuuuuu(
            IntPtr thisptr, int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort, ref uint punFlags,
            ref uint pRTime32LastPlayedOnServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeAddFavoriteGameUuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, uint unFlags, uint rTime32LastPlayedOnServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRemoveFavoriteGameUuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, uint unFlags);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeGetFavoriteGame2Iuuuuuu(
            IntPtr thisptr, int iGame, ref uint pnAppId, ref uint pnIp, ref ushort pnConnPort, ref ushort pnQueryPort,
            ref uint punFlags, ref uint pRTime32LastPlayedOnServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeAddFavoriteGame2Uuuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags,
            uint rTime32LastPlayedOnServer);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRemoveFavoriteGame2Uuuuu(
            IntPtr thisptr, uint nAppId, uint nIp, ushort nConnPort, ushort nQueryPort, uint unFlags);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRequestLobbyListUmu(
            IntPtr thisptr, ulong ulGameId, ref MatchMakingKeyValuePairT pFilters, uint nFilters);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyByIndexI(IntPtr thisptr, ref ulong retarg, int iLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeCreateLobbyUb(
            IntPtr thisptr, ulong ulGameId, [MarshalAs(UnmanagedType.I1)] bool bPrivate);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeJoinLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeLeaveLobbyC(IntPtr thisptr, ulong steamIdLobby);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeInviteUserToLobbyCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdInvitee);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetNumLobbyMembersC(IntPtr thisptr, ulong steamIdLobby);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetLobbyMemberByIndexCi(
            IntPtr thisptr, ref ulong retarg, ulong steamIdLobby, int iMember);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyDataCs(IntPtr thisptr, ulong steamIdLobby, string pchKey);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyDataCss(IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLobbyMemberDataCcs(
            IntPtr thisptr, ulong steamIdLobby, ulong steamIdUser, string pchKey);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetLobbyMemberDataCss(
            IntPtr thisptr, ulong steamIdLobby, string pchKey, string pchValue);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeChangeLobbyAdminCc(IntPtr thisptr, ulong steamIdLobby, ulong steamIdNewAdmin);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSendLobbyChatMsgCbi(
            IntPtr thisptr, ulong steamIdLobby, byte[] pvMsgBody, int cubMsgBody);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLobbyChatEntryCicbie(
            IntPtr thisptr, ulong steamIdLobby, int iChatId, ref ulong pSteamIdUser, byte[] pvData, int cubData,
            ref EChatEntryType peChatEntryType);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeRequestLobbyDataC(IntPtr thisptr, ulong steamIdLobby);
    };
}