// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamUser009VTable
    {
        public IntPtr GetHSteamUser0;
        public IntPtr BLoggedOn1;
        public IntPtr GetSteamID2;
        public IntPtr InitiateGameConnection3;
        public IntPtr TerminateGameConnection4;
        public IntPtr TrackAppUsageEvent5;
        public IntPtr RefreshSteam2Login6;
        private IntPtr DTorISteamUser0097;
    };

    [InteropHelp.InterfaceVersionAttribute("SteamUser009")]
    public class SteamUser009 : InteropHelp.NativeWrapper<SteamUser009VTable>
    {
        public int GetHSteamUser()
        {
            return GetFunction<NativeGetHSteamUser>(Functions.GetHSteamUser0)(ObjectAddress);
        }

        public bool BLoggedOn()
        {
            return GetFunction<NativeBLoggedOn>(Functions.BLoggedOn1)(ObjectAddress);
        }

        public CSteamId GetSteamId()
        {
            ulong ret = 0;
            GetFunction<NativeGetSteamId>(Functions.GetSteamID2)(ObjectAddress, ref ret);
            return new CSteamId(ret);
        }

        public int InitiateGameConnection(byte[] pBlob, CSteamId steamId, CGameId gameId, uint unIpServer,
            ushort usPortServer, bool bSecure)
        {
            return GetFunction<NativeInitiateGameConnectionBiccuub>(Functions.InitiateGameConnection3)(ObjectAddress,
                pBlob, pBlob.Length, steamId.ConvertToUint64(), gameId.ConvertToUint64(), unIpServer, usPortServer,
                bSecure);
        }

        public void TerminateGameConnection(uint unIpServer, ushort usPortServer)
        {
            GetFunction<NativeTerminateGameConnectionUu>(Functions.TerminateGameConnection4)(ObjectAddress, unIpServer,
                usPortServer);
        }

        public void TrackAppUsageEvent(CGameId gameId, EAppUsageEvent eAppUsageEvent, string pchExtraInfo)
        {
            GetFunction<NativeTrackAppUsageEventCes>(Functions.TrackAppUsageEvent5)(ObjectAddress,
                gameId.ConvertToUint64(), eAppUsageEvent, pchExtraInfo);
        }

        public void RefreshSteam2Login()
        {
            GetFunction<NativeRefreshSteam2Login>(Functions.RefreshSteam2Login6)(ObjectAddress);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetHSteamUser(IntPtr thisptr);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeBLoggedOn(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeGetSteamId(IntPtr thisptr, ref ulong retarg);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeInitiateGameConnectionBiccuub(
            IntPtr thisptr, byte[] pBlob, int cbMaxBlob, ulong steamId, ulong gameId, uint unIpServer,
            ushort usPortServer, [MarshalAs(UnmanagedType.I1)] bool bSecure);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeTerminateGameConnectionUu(IntPtr thisptr, uint unIpServer, ushort usPortServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeTrackAppUsageEventCes(
            IntPtr thisptr, ulong gameId, EAppUsageEvent eAppUsageEvent, string pchExtraInfo);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRefreshSteam2Login(IntPtr thisptr);
    };
}