// This file is automatically generated.

using System;
using System.Runtime.InteropServices;
using System.Text;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class Steam2Bridge001VTable
    {
        public IntPtr SetSteam2Ticket0;
        public IntPtr SetAccountName1;
        public IntPtr SetPassword2;
        public IntPtr SetAccountCreationTime3;
        public IntPtr CreateProcess4;
        public IntPtr GetConnectedUniverse5;
        public IntPtr GetIPCountry6;
        public IntPtr GetNumLicenses7;
        public IntPtr GetLicensePackageID8;
        public IntPtr GetLicenseTimeCreated9;
        public IntPtr GetLicenseTimeNextProcess10;
        public IntPtr GetLicenseMinuteLimit11;
        public IntPtr GetLicenseMinutesUsed12;
        public IntPtr GetLicensePaymentMethod13;
        public IntPtr GetLicenseFlags14;
        public IntPtr GetLicensePurchaseCountryCode15;
        public IntPtr SetOfflineMode16;
        private IntPtr DTorISteam2Bridge00117;
    };

    [InteropHelp.InterfaceVersionAttribute("STEAM2BRIDGE_INTERFACE_VERSION001")]
    public class Steam2Bridge001 : InteropHelp.NativeWrapper<Steam2Bridge001VTable>
    {
        public void SetSteam2Ticket(byte[] pubTicket)
        {
            GetFunction<NativeSetSteam2TicketBi>(Functions.SetSteam2Ticket0)(ObjectAddress, pubTicket, pubTicket.Length);
        }

        public bool SetAccountName(string pchAccountName)
        {
            return GetFunction<NativeSetAccountNameS>(Functions.SetAccountName1)(ObjectAddress, pchAccountName);
        }

        public bool SetPassword(string pchPassword)
        {
            return GetFunction<NativeSetPasswordS>(Functions.SetPassword2)(ObjectAddress, pchPassword);
        }

        public bool SetAccountCreationTime(uint rt)
        {
            return GetFunction<NativeSetAccountCreationTimeU>(Functions.SetAccountCreationTime3)(ObjectAddress, rt);
        }

        public bool CreateProcess(byte[] lpVacBlob, string lpApplicationName, StringBuilder lpCommandLine,
            uint dwCreationFlags, byte[] lpEnvironment, StringBuilder lpCurrentDirectory, uint nGameId)
        {
            return GetFunction<NativeCreateProcessBussubsu>(Functions.CreateProcess4)(ObjectAddress, lpVacBlob,
                (uint)lpVacBlob.Length, lpApplicationName, lpCommandLine, dwCreationFlags, lpEnvironment,
                lpCurrentDirectory, nGameId);
        }

        public EUniverse GetConnectedUniverse()
        {
            return GetFunction<NativeGetConnectedUniverse>(Functions.GetConnectedUniverse5)(ObjectAddress);
        }

        public string GetIpCountry()
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(GetFunction<NativeGetIpCountry>(Functions.GetIPCountry6)(ObjectAddress)));
        }

        public uint GetNumLicenses()
        {
            return GetFunction<NativeGetNumLicenses>(Functions.GetNumLicenses7)(ObjectAddress);
        }

        public int GetLicensePackageId(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicensePackageIdu>(Functions.GetLicensePackageID8)(ObjectAddress, nLicenseIndex);
        }

        public uint GetLicenseTimeCreated(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicenseTimeCreatedU>(Functions.GetLicenseTimeCreated9)(ObjectAddress,
                nLicenseIndex);
        }

        public uint GetLicenseTimeNextProcess(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicenseTimeNextProcessU>(Functions.GetLicenseTimeNextProcess10)(ObjectAddress,
                nLicenseIndex);
        }

        public int GetLicenseMinuteLimit(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicenseMinuteLimitU>(Functions.GetLicenseMinuteLimit11)(ObjectAddress,
                nLicenseIndex);
        }

        public int GetLicenseMinutesUsed(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicenseMinutesUsedU>(Functions.GetLicenseMinutesUsed12)(ObjectAddress,
                nLicenseIndex);
        }

        public EPaymentMethod GetLicensePaymentMethod(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicensePaymentMethodU>(Functions.GetLicensePaymentMethod13)(ObjectAddress,
                nLicenseIndex);
        }

        public ELicenseFlags GetLicenseFlags(uint nLicenseIndex)
        {
            return GetFunction<NativeGetLicenseFlagsU>(Functions.GetLicenseFlags14)(ObjectAddress, nLicenseIndex);
        }

        public string GetLicensePurchaseCountryCode(uint nLicenseIndex)
        {
            return
                InteropHelp.DecodeAnsiReturn(
                    Marshal.PtrToStringAnsi(
                        GetFunction<NativeGetLicensePurchaseCountryCodeU>(Functions.GetLicensePurchaseCountryCode15)(
                            ObjectAddress, nLicenseIndex)));
        }

        public bool SetOfflineMode(bool bOffline)
        {
            return GetFunction<NativeSetOfflineModeB>(Functions.SetOfflineMode16)(ObjectAddress, bOffline);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeSetSteam2TicketBi(IntPtr thisptr, byte[] pubTicket, int cubTicket);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetAccountNameS(IntPtr thisptr, string pchAccountName);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetPasswordS(IntPtr thisptr, string pchPassword);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetAccountCreationTimeU(IntPtr thisptr, uint rt);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeCreateProcessBussubsu(
            IntPtr thisptr, byte[] lpVacBlob, uint cbBlobSize, string lpApplicationName, StringBuilder lpCommandLine,
            uint dwCreationFlags, byte[] lpEnvironment, StringBuilder lpCurrentDirectory, uint nGameId);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EUniverse NativeGetConnectedUniverse(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetIpCountry(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetNumLicenses(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLicensePackageIdu(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetLicenseTimeCreatedU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate uint NativeGetLicenseTimeNextProcessU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLicenseMinuteLimitU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate int NativeGetLicenseMinutesUsedU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate EPaymentMethod NativeGetLicensePaymentMethodU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate ELicenseFlags NativeGetLicenseFlagsU(IntPtr thisptr, uint nLicenseIndex);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate IntPtr NativeGetLicensePurchaseCountryCodeU(IntPtr thisptr, uint nLicenseIndex);

        [return: MarshalAs(UnmanagedType.I1)]
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate bool NativeSetOfflineModeB(IntPtr thisptr, [MarshalAs(UnmanagedType.I1)] bool bOffline);
    };
}