// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    public enum EMatchMakingServerResponse
    {
        EServerResponded = 0,
        EServerFailedToRespond = 1,
        ENoServersListedOnMasterServer = 2
    };

    public enum EMatchMakingType
    {
        EInternetServer = 0,
        ELanServer = 1,
        EFriendsServer = 2,
        EFavoritesServer = 3,
        EHistoryServer = 4,
        ESpectatorServer = 5,
        EInvalidServer = 6
    };

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmakingServerListResponse001VTable
    {
        public IntPtr ServerResponded0;
        public IntPtr ServerFailedToRespond1;
        public IntPtr RefreshComplete2;
        private IntPtr DTorISteamMatchmakingServerListResponse0013;
    };

    public class SteamMatchmakingServerListResponse001 :
        InteropHelp.NativeWrapper<SteamMatchmakingServerListResponse001VTable>
    {
        public void ServerResponded(int iServer)
        {
            GetFunction<NativeServerRespondedI>(Functions.ServerResponded0)(ObjectAddress, iServer);
        }

        public void ServerFailedToRespond(int iServer)
        {
            GetFunction<NativeServerFailedToRespondI>(Functions.ServerFailedToRespond1)(ObjectAddress, iServer);
        }

        public void RefreshComplete(EMatchMakingServerResponse response)
        {
            GetFunction<NativeRefreshCompleteE>(Functions.RefreshComplete2)(ObjectAddress, response);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerRespondedI(IntPtr thisptr, int iServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerFailedToRespondI(IntPtr thisptr, int iServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRefreshCompleteE(IntPtr thisptr, EMatchMakingServerResponse response);
    };

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmakingServerListResponse002VTable
    {
        public IntPtr ServerResponded0;
        public IntPtr ServerFailedToRespond1;
        public IntPtr RefreshComplete2;
        private IntPtr DTorISteamMatchmakingServerListResponse0023;
    };

    public class SteamMatchmakingServerListResponse002 :
        InteropHelp.NativeWrapper<SteamMatchmakingServerListResponse002VTable>
    {
        public void ServerResponded(byte[] hRequest)
        {
            GetFunction<NativeServerRespondedBi>(Functions.ServerResponded0)(ObjectAddress, hRequest, hRequest.Length);
        }

        public void ServerFailedToRespond(byte[] hRequest)
        {
            GetFunction<NativeServerFailedToRespondBi>(Functions.ServerFailedToRespond1)(ObjectAddress, hRequest,
                hRequest.Length);
        }

        public void RefreshComplete(byte[] hRequest, EMatchMakingServerResponse response)
        {
            GetFunction<NativeRefreshCompleteBe>(Functions.RefreshComplete2)(ObjectAddress, hRequest, response);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerRespondedBi(IntPtr thisptr, byte[] hRequest, int iServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerFailedToRespondBi(IntPtr thisptr, byte[] hRequest, int iServer);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRefreshCompleteBe(
            IntPtr thisptr, byte[] hRequest, EMatchMakingServerResponse response);
    };

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmakingPingResponseVTable
    {
        public IntPtr ServerResponded0;
        public IntPtr ServerFailedToRespond1;
        private IntPtr DTorISteamMatchmakingPingResponse2;
    };

    public class SteamMatchmakingPingResponse : InteropHelp.NativeWrapper<SteamMatchmakingPingResponseVTable>
    {
        public void ServerResponded(GameserveritemT server)
        {
            GetFunction<NativeServerRespondedG>(Functions.ServerResponded0)(ObjectAddress, server);
        }

        public void ServerFailedToRespond()
        {
            GetFunction<NativeServerFailedToRespond>(Functions.ServerFailedToRespond1)(ObjectAddress);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerRespondedG(IntPtr thisptr, GameserveritemT server);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeServerFailedToRespond(IntPtr thisptr);
    };

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmakingPlayersResponseVTable
    {
        public IntPtr AddPlayerToList0;
        public IntPtr PlayersFailedToRespond1;
        public IntPtr PlayersRefreshComplete2;
        private IntPtr DTorISteamMatchmakingPlayersResponse3;
    };

    public class SteamMatchmakingPlayersResponse : InteropHelp.NativeWrapper<SteamMatchmakingPlayersResponseVTable>
    {
        public void AddPlayerToList(string pchName, int nScore, float flTimePlayed)
        {
            GetFunction<NativeAddPlayerToListSif>(Functions.AddPlayerToList0)(ObjectAddress, pchName, nScore,
                flTimePlayed);
        }

        public void PlayersFailedToRespond()
        {
            GetFunction<NativePlayersFailedToRespond>(Functions.PlayersFailedToRespond1)(ObjectAddress);
        }

        public void PlayersRefreshComplete()
        {
            GetFunction<NativePlayersRefreshComplete>(Functions.PlayersRefreshComplete2)(ObjectAddress);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeAddPlayerToListSif(IntPtr thisptr, string pchName, int nScore, float flTimePlayed);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativePlayersFailedToRespond(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativePlayersRefreshComplete(IntPtr thisptr);
    };

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public class SteamMatchmakingRulesResponseVTable
    {
        public IntPtr RulesResponded0;
        public IntPtr RulesFailedToRespond1;
        public IntPtr RulesRefreshComplete2;
        private IntPtr DTorISteamMatchmakingRulesResponse3;
    };

    public class SteamMatchmakingRulesResponse : InteropHelp.NativeWrapper<SteamMatchmakingRulesResponseVTable>
    {
        public void RulesResponded(string pchRule, string pchValue)
        {
            GetFunction<NativeRulesRespondedSs>(Functions.RulesResponded0)(ObjectAddress, pchRule, pchValue);
        }

        public void RulesFailedToRespond()
        {
            GetFunction<NativeRulesFailedToRespond>(Functions.RulesFailedToRespond1)(ObjectAddress);
        }

        public void RulesRefreshComplete()
        {
            GetFunction<NativeRulesRefreshComplete>(Functions.RulesRefreshComplete2)(ObjectAddress);
        }

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRulesRespondedSs(IntPtr thisptr, string pchRule, string pchValue);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRulesFailedToRespond(IntPtr thisptr);

        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        private delegate void NativeRulesRefreshComplete(IntPtr thisptr);
    };
}