// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct ServernetadrT
    {
        public ushort m_usConnectionPort;
        public ushort m_usQueryPort;
        public uint m_unIP;
    };
}