// This file is automatically generated.

using System;
using System.Runtime.InteropServices;

namespace Steam4Net
{
    public enum ELobbyType
    {
        KeLobbyTypePrivate = 0,
        KeLobbyTypeFriendsOnly = 1,
        KeLobbyTypePublic = 2,
        KeLobbyTypeInvisible = 3
    };

    public enum ENotificationPosition
    {
        KePositionTopLeft = 0,
        KePositionTopRight = 1,
        KePositionBottomLeft = 2,
        KePositionBottomRight = 3
    };

    public enum EChatMemberStateChange
    {
        KeChatMemberStateChangeEntered = 1,
        KeChatMemberStateChangeLeft = 2,
        KeChatMemberStateChangeDisconnected = 4,
        KeChatMemberStateChangeKicked = 8,
        KeChatMemberStateChangeBanned = 16
    };

    public enum EServerMode
    {
        EServerModeInvalid = 0,
        EServerModeNoAuthentication = 1,
        EServerModeAuthentication = 2,
        EServerModeAuthenticationAndSecure = 3
    };

    public enum EUniverse
    {
        KeUniverseInvalid = 0,
        KeUniversePublic = 1,
        KeUniverseBeta = 2,
        KeUniverseInternal = 3,
        KeUniverseDev = 4,
        KeUniverseMax = 5
    };

    public enum ShareTypeT
    {
        ShareStopimmediately = 0,
        ShareRatio = 1,
        ShareManual = 2
    };

    public enum EChatSteamIdInstanceFlags
    {
        KeChatAccountInstanceMask = 4095,
        KeChatInstanceFlagClan = 524288,
        KeChatInstanceFlagLobby = 262144,
        KeChatInstanceFlagMmsLobby = 131072
    };

    public enum ECallbackType
    {
        KiSteamUserCallbacks = 100,
        KiSteamGameServerCallbacks = 200,
        KiSteamFriendsCallbacks = 300,
        KiSteamBillingCallbacks = 400,
        KiSteamMatchmakingCallbacks = 500,
        KiSteamContentServerCallbacks = 600,
        KiSteamUtilsCallbacks = 700,
        KiClientFriendsCallbacks = 800,
        KiClientUserCallbacks = 900,
        KiSteamAppsCallbacks = 1000,
        KiSteamUserStatsCallbacks = 1100,
        KiSteamNetworkingCallbacks = 1200,
        KiClientRemoteStorageCallbacks = 1300,
        KiSteamUserItemsCallbacks = 1400,
        KiSteamGameServerItemsCallbacks = 1500,
        KiClientUtilsCallbacks = 1600,
        KiSteamGameCoordinatorCallbacks = 1700,
        KiSteamGameServerStatsCallbacks = 1800,
        KiSteam2AsyncCallbacks = 1900,
        KiSteamGameStatsCallbacks = 2000,
        KiClientHttpCallbacks = 2100,
        KiClientScreenshotsCallbacks = 2200,
        KiSteamScreenshotsCallbacks = 2300,
        KiClientAudioCallbacks = 2400,
        KiSteamUnifiedMessagesCallbacks = 2500,
        KiClientUnifiedMessagesCallbacks = 2600
    };

    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct CallbackMsgT
    {
        public int m_hSteamUser;
        public int m_iCallback;
        public IntPtr m_pubParam;
        public int m_cubParam;
    };
}