// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct SteamPrepurchaseInfo
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 21)]
        public string szTypeOfProofOfPurchase;

        public uint uLengthOfBinaryProofOfPurchaseToken;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 201)]
        public string cBinaryProofOfPurchaseToken;
    };
}