// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct SteamExternalBillingInfo
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 101)]
        public string szAccountName;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 81)]
        public string szPassword;
    };
}