// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct SteamProgress
    {
        public int bValid;
        public uint uPercentDone;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 255)]
        public string szProgress;
    };
}