// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct SteamUpdateStats
    {
        public ulong uBytesTotal;
        public ulong uBytesPresent;
    };
}