// This file is automatically generated.

using System.Runtime.InteropServices;

namespace Steam4Net
{
    [StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct SteamAppDependencyInfo
    {
        public uint AppId;
        public uint IsRequired;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 255)]
        public string szMountName;
    };
}